### ISSUE TITLE
Missing customization options 

### ISSUE THREAD

**Issue by pancho111203** [auth0/react-native-lock#104]
There are many customization options available in the Lock library, but most of them don't seem to be supported by react-native-lock.

More specifically, I'm talking about being able to set the social button to use a long image (it looks ugly being small when there is only one social connection).

[Docs](https://auth0.com/docs/libraries/lock/v10/customization#socialbuttonstyle-string-)

```
var options = {
  socialButtonStyle: 'big'
};
```

Maybe there is a way to add this from Objective C code directly. If so, I haven't been able to find it.

**Comment by hzalaz** [comment]
@pancho111203 those options are for a different lock not the react-native lock. We are not planning to add those options to this current version but will reevaluate once we start working in a next version
