### ISSUE TITLE
Android application keeps stopping 

### ISSUE THREAD

**Issue by seacloud9** [auth0/react-native-lock#106]
I recently had this issue:
![authentication_problem](https://cloud.githubusercontent.com/assets/640305/20776441/7c106126-b715-11e6-8e49-5a74015683d4.png)
I followed this tutorial https://auth0.com/docs/quickstart/native/react-native-android and it looks like react-native-lock uses an older version of react-native.  We are currently on version 38 the latest; around version 29 MainActivity and MainApplication were separated so this section does not really work for the current state of react-native.

![mainactivity](https://cloud.githubusercontent.com/assets/640305/20776556/25dbe6b2-b716-11e6-953c-49840f346448.png)

I changed the Main Activity Code to what is shown below:

```
public class MainApplication extends Application implements ReactApplication {
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }
    @Override
    protected List<ReactPackage> getPackages() {
      LockReactPackage lockReactPackage = new LockReactPackage();
      lockReactPackage.addIdentityProvider(Strategies.GooglePlus, new GooglePlusIdentityProvider(MainApplication.this));
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new VectorIconsPackage(),
            new MapsPackage(),
            new ReactNativeI18n(),
            new RNDeviceInfo(),
            new RNSvgPackage(),
            new OrientationPackage(),
            lockReactPackage,
            new ReactNativeConfigPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

Currently the Application works on iOS but on Android after doing the updates to get it to work with the google play services and installing the SHA-1 keys that are stored in the google-services.json it will build but it fails immediately in the emulator as shown below:

![application_fails_to_load_](https://cloud.githubusercontent.com/assets/640305/20776608/7ed8f7aa-b716-11e6-948c-66f2613a87da.png)

Has any one else had this issue? I am going to do more debugging but any suggestions would be greatly appreciated thanks.

**Comment by hzalaz** [comment]
@seacloud9 we are going to need the exception trace from android to see why it crashed. It could even be an error unrelated to lock

**Comment by seacloud9** [comment]
@hzalaz thanks found the issue I had everything todo with the way google services were being initialized I changed my gradle.build (app) dependencies to the following and it worked.


```
dependencies {
    compile project(':react-native-lock')
    compile project(':react-native-orientation')
    compile project(':react-native-svg')
    compile project(':react-native-vector-icons')
    compile project(':react-native-maps')
    compile project(':react-native-i18n')
    compile project(':react-native-device-info')
    compile project(':react-native-config')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile 'com.auth0.android:lock-googleplus:2.3.+'
    compile 'com.google.android.gms:play-services:9.0.0'
    compile 'com.google.android.gms:play-services-auth:9.8.0'
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```
Thanks

**Comment by kaushal9678** [comment]
### **Just clean your build in Android Studio and then rebuild your project then run.** 
**_You will get some file path or some package that you called is missing._ You will see that on terminal and emulator.**

**Comment by farhankassam2** [comment]
> @hzalaz thanks found the issue I had everything todo with the way google services were being initialized I changed my gradle.build (app) dependencies to the following and it worked.
> 
> ```
> dependencies {
>     compile project(':react-native-lock')
>     compile project(':react-native-orientation')
>     compile project(':react-native-svg')
>     compile project(':react-native-vector-icons')
>     compile project(':react-native-maps')
>     compile project(':react-native-i18n')
>     compile project(':react-native-device-info')
>     compile project(':react-native-config')
>     compile fileTree(dir: "libs", include: ["*.jar"])
>     compile 'com.auth0.android:lock-googleplus:2.3.+'
>     compile 'com.google.android.gms:play-services:9.0.0'
>     compile 'com.google.android.gms:play-services-auth:9.8.0'
>     compile "com.android.support:appcompat-v7:23.0.1"
>     compile "com.facebook.react:react-native:+"  // From node_modules
> }
> ```
> 
> Thanks

@seacloud9 I am facing this same issue and I do not understand how to resolve it. The above code you added to your `build.gradle` (app), does it manually compile some of these dependencies? If so, why should you manually compile them when running the app automatically installs and extracts the packages in your code when you import these packages?

Could you further elaborate on how having those compilation statements prevents the app to suddenly stop (the way it is shown in the screenshot)?


Thanks.

**Comment by seacloud9** [comment]
@farhankassam2 it has been a while since I had this issue.  I believe it happens when there is a dependency mismatch.  I would spend some time looking at your packages also make sure the private keys its need is set up properly.
