### ISSUE TITLE
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2)

### ISSUE THREAD

**Issue by kirkstrobeck** [auth0/react-native-lock#109]
I cannot get this project to work on a fresh project from `react-native init awesome`

Dependencies

- "react": "15.4.1",
- "react-native": "0.39.2",
- "react-native-lock": "^0.4.0"

```bash
** BUILD FAILED **



The following build commands failed:
  CompileC /Users/kirkstrobeck/awesome/ios/build/Build/Intermediates/A0RNLock.build/Debug-iphonesimulator/A0RNLock.build/Objects-normal/x86_64/A0LockReact.o A0RNLock/Core/A0LockReact.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/awesome.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/awesome.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by Vikaton** [comment]
I get this error as well

**Comment by krzysztofp** [comment]
Same problem here

**Comment by NoahGrumman** [comment]
I get this as well.

**Comment by iannyanes** [comment]
Bug Reproduced - Adding to the fixing pipeline

**Comment by iannyanes** [comment]
@NoahGrumman @krzysztofp @Vikaton @kirkstrobeck Did you download the sample code from https://auth0.com/docs/quickstart/native/react-native-ios or you just forked https://github.com/auth0/react-native-lock ?

**Comment by Vikaton** [comment]
I believe I downloaded it

**Comment by hzalaz** [comment]
I believe is an old react native issue unrelated to lock https://github.com/facebook/react-native/issues/7308

**Comment by kirkstrobeck** [comment]
So you’re saying that the whole react native project is broken and this is a `wontfix`? 

This issue no longer affects me, because I already pivoted away from auth0. I made the right decision, because [that response](https://github.com/auth0/react-native-lock/issues/109#issuecomment-271907246) is unreal.

**Comment by hzalaz** [comment]
@kirkstrobeck I am saying that the error is not caused by lock but by the react-native integration with Xcode that seemed  to fail for some people. Xcode tooling is kinda brittle when you are doing thing that are not apple way (I learned this the hard way) and the last [comment](https://github.com/facebook/react-native/issues/7308#issuecomment-271857720) mentioned what is wrong and how to fix it.

Sorry hearing that you pivoted away from Auth0 but the only error where I can see some information is 

```
Installing build/Build/Products/Debug-iphonesimulator/awesome.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/awesome.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```
which is what I answered in my unreal response. 

```
The following build commands failed:
  CompileC /Users/kirkstrobeck/awesome/ios/build/Build/Intermediates/A0RNLock.build/Debug-iphonesimulator/A0RNLock.build/Objects-normal/x86_64/A0LockReact.o A0RNLock/Core/A0LockReact.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

The other line might hide another issue but without the full log, what steps you followed to get that error I can only guess what's wrong.

@Vikaton @NoahGrumman @krzysztofp if you can provide more information or a sample repo we could debug, that will help.

**Comment by kirkstrobeck** [comment]
Just a vanilla project https://facebook.github.io/react-native/docs/getting-started.html

**Comment by hzalaz** [comment]
@kirkstrobeck probably my english is not good since I am not a native speaker but can you provide the full log when the build fails?

**Comment by kirkstrobeck** [comment]
Thanks for the response. I don’t have time to generate those logs again, but if you create a [default project](https://facebook.github.io/react-native/docs/getting-started.html) on React Native, which is their "Hello World" that always works, and then follow the [steps listed here](https://github.com/auth0/react-native-lock) you should be able to reproduce it locally.

**Comment by ljhskyso** [comment]
I am having this issue while init a new RN project. what can i do? LOL

**Comment by gutouyu** [comment]
I got this too with the default project. what can I do?

**Comment by wxb2939** [comment]
download boost_1_63_0 jar ,replace node_modules/react-native/third-party/boost_1_63_0. I solve it.

**Comment by haifaGh** [comment]
Hey guys .. I'm having a problem and I spent a few hours trying to solve but i couldn't .. I could really use your help. so here is the error i get every time i run my app (this first time i get this kind of errors for a while using react native ):

An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "application-name" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "application-name" is unknown to FrontBoard").

Please any idea .. thanks

**Comment by allexysleeps** [comment]
Hi guys. Getting similar issue on latest node/xcode/react-native. 
Cant even init AwesomeProject
Couldn't fix it. 
I can provide full log. pls help.

`
** BUILD FAILED **


The following commands produced analyzer issues:

	Analyze /Users/alexeyshulev/Coding/Learning/React-Native/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
(1 command with analyzer issues)

The following build commands failed:
	Analyze /Users/alexeyshulev/Coding/Learning/React-Native/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	CompileC /Users/alexeyshulev/Coding/Learning/React-Native/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/yoga.build/Objects-normal/x86_64/YGNodeList.o /Users/alexeyshulev/Coding/Learning/React-Native/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/alexeyshulev/Coding/Learning/React-Native/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/yoga.build/Objects-normal/x86_64/Yoga.o /Users/alexeyshulev/Coding/Learning/React-Native/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

**Comment by nsnarvekar** [comment]
I am also facing this issue from last week. Not able to build my project.

fatal error: 'config.h' file not found

`In file included from /Users/nikhiln/Documents/Nikhil/R&D/newProj/node_modules/react-native/third-party/glog-0.3.4/src/symbolize.cc:55:
In file included from /Users/nikhiln/Documents/Nikhil/R&D/newProj/node_modules/react-native/React/../third-party/glog-0.3.4/src/utilities.h:73:
/Users/nikhiln/Documents/Nikhil/R&D/newProj/node_modules/react-native/React/../third-party/glog-0.3.4/src/base/mutex.h:105:10: fatal error: 'config.h' file not found
#include "config.h"           // to figure out pthreads support
         ^


** BUILD FAILED **


The following build commands failed:

	CompileC /Users/nikhiln/Documents/Nikhil/R&D/newProj/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/utilities.o /Users/nikhiln/Documents/Nikhil/R&D/newProj/node_modules/react-native/third-party/glog-0.3.4/src/utilities.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/newProj.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/newProj.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

**Comment by nsnarvekar** [comment]
I got the answer.

**Comment by nsnarvekar** [comment]
I got the answer.
ReactNative script wasnt working because my project was in "R&D" folder. I think Script wasnt able to read the special characters in path.
Created new project on desktop and its working.

**Comment by WLunc** [comment]
I delete ~/.curlrc...

**Comment by popo63301** [comment]
@nsnarvekar Worked for me. When I run pwd command I got something like this xxx/xxxx/xxx/react native/Cross (cross is my project name which is inside of a folder called "react native"). Then I created a new folder instead of xxx/xxxx/xxx/RCTnatived/AwesomeProject (RCTnatived as a random name, so don't bother about the "d" at the end) and it works perfectly. 

So, if you don't have spaces in your project name and still have this problem, be careful of the folders located **before** your current React Native project.

**Comment by iskandar625** [comment]
I have created new react native project using "react-native init HelloWorld".
When I tried "react-native run-ios", I got this error.
Here's a log:

** BUILD FAILED **


The following commands produced analyzer issues:
	Analyze /Volumes/Work/React\ Native/HelloWorld/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Volumes/Work/React\ Native/HelloWorld/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c

(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Volumes/Work/React\ Native/HelloWorld/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/HelloWorld.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/HelloWorld.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Somebody help me please.

**Comment by rodiwa** [comment]
Here's what I did to reproduce the issue
1. Created new folder on desktop called xcode
2. From terminal, i did a `react-native albums init` (_albums_ is the name of the project)
3. After all dependencies are installed, I cd'ed into albums directory and did a `react-native run-ios`.
4. The simulator starts up, but the application does not load.
5. I get the following error in log:


```
** BUILD FAILED **

The following build commands failed:

CompileC /Users/rohit/Desktop/xcode/albums/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/Conv.o /Users/rohit/Desktop/xcode/albums/node_modules/react-native/third-party/folly-2016.09.26.00/folly/Conv.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/albums.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/albums.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Versions I am using
react-native-cli 2.0.1
react-native 0.47.1
node 6.9.5
npm 4.1.2

**Comment by popo63301** [comment]
@AndreyHomenko and @misaal9 , could you both run "pwd" command (inside your project directory) so as to see what's the path of your project?

**Comment by jomadoye** [comment]
I also have this issue.

**Comment by iskandar625** [comment]
I solved the issue yesterday.
The problem was with the project path.
There must be no folder in the path which has a space in the name.
In my case the parent folder name was 'React Native'.
I renamed it 'ReactNative' and it's working well.
I am really happy if this helped you.
Andrey

**Comment by divsbhalala** [comment]
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks build/Build/Intermediates.noindex/Accelevents.build/Release-iphonesimulator/Accelevents.build/Script-5A234723829AC4025075888E.sh
    cd /Users/divsbhalala/Documents/Jon/react-native-starter-app/ios
    /bin/sh -c /Users/divsbhalala/Documents/Jon/react-native-starter-app/ios/build/Build/Intermediates.noindex/Accelevents.build/Release-iphonesimulator/Accelevents.build/Script-5A234723829AC4025075888E.sh

mkdir -p /Users/divsbhalala/Documents/Jon/react-native-starter-app/ios/build/Build/Products/Release-iphonesimulator/Accelevents.app/Frameworks



** BUILD SUCCEEDED **


Installing build/Build/Products/release-iphonesimulator/Accelevents.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Launching com.dev.Accelevents
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.dev.Accelevents" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.dev.Accelevents" is unknown to FrontBoard").
com.dev.Accelevents: -1

Process finished with exit code 0

**Comment by yasircs4** [comment]
I have the same issue.

**Comment by xaphod** [comment]
Cloned a large project, same issue. No spaces in any part of the path.

**Comment by firebellys** [comment]
Also seeing this issue. Still investigating.

**Comment by AishwaryaSurana** [comment]
Try this:

Goto XCode -> Click your project folder -> click General -> under sigining tab select a development team .

Dont forget to connect your IPhone as well.

**Comment by 2075** [comment]
in certain cases, xcode gets confused. for example, when renaming the project on filesystem level, inside your code editor or inside xcode. it seems like the references get lost and cant be rebuilt.

**Comment by Luckygirlllll** [comment]
I have the same issue, no spaces or special symbols in the project path

**Comment by digital-flowers** [comment]
just open xcode and close it and it will work

**Comment by khadkaPratik** [comment]
Hello everyone ,
I have been going through the following error when ever i run react native run ios though the project runs fine but the error is still there 

** BUILD FAILED **



The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/Project.app/Project normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/Project.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Project.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by pytlakow** [comment]
@khadkaPratik I had the same issue until I updated to Xcode 9

**Comment by nehabhamare** [comment]
I updated Xcode and seems like the biggest mistake of my life. Stuck with the same error since 2 days:

In file included from /Users/nehabhamare/Documents/projects/safechem-react-native/node_modules/react-native/Libraries/Network/RCTFileRequestHandler.m:10:
/Users/nehabhamare/Documents/projects/safechem-react-native/node_modules/react-native/Libraries/Network/RCTFileRequestHandler.h:10:9: fatal error: 'React/RCTInvalidating.h' file not found
#import <React/RCTInvalidating.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~


** BUILD FAILED **



The following commands produced analyzer issues:
        Analyze /Users/nehabhamare/Documents/projects/safechem-react-native/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
        Analyze /Users/nehabhamare/Documents/projects/safechem-react-native/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
        Analyze Base/RCTModuleMethod.mm
        Analyze RCTNetworkTask.m
        Analyze RCTFileRequestHandler.m
(5 commands with analyzer issues)

The following build commands failed:
        CompileC build/RCTNetwork.build/Debug-iphonesimulator/RCTNetwork.build/Objects-normal/x86_64/RCTNetworkTask.o RCTNetworkTask.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC build/RCTNetwork.build/Debug-iphonesimulator/RCTNetwork.build/Objects-normal/x86_64/RCTDataRequestHandler.o RCTDataRequestHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        Analyze RCTNetworkTask.m
(3 failures)

Installing build/Build/Products/Debug-iphonesimulator/Safechem.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Safechem.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by khadkaPratik** [comment]
@nehabhamare What was the last package u added ??

**Comment by nehabhamare** [comment]
@khadkaPratik I think I updated react-native and tried to archieve the project after that.It showed a problem with provisioning profile and so I changed the bundle identifier. After that it started showing really weird errors. I tried going to older version of Xcode and also tried installing older versions of react native but nothing works! And this is the error that I get in Phpstorm. If I try to open it in Xcode then it gives the error:
![image](https://user-images.githubusercontent.com/21045231/38419980-a2bfe36c-39a2-11e8-9247-1658970228d7.png)

**Comment by khadkaPratik** [comment]
If this is a new project y can try 

> try making backup before experimenting with your project

> rm -rf node_modules/  ios/  android/

> npm install  & react-native-upgrade 

You this for only as ur Last Resort [Find it here ](https://stackoverflow.com/questions/49519949/build-fail-for-google-signin-package-in-react-native/49653047#49653047)

**Comment by nehabhamare** [comment]
Thanks @khadkaPratik for your response but I have tried these steps already. Unfortunately it doesn't work in my case somehow. I have backed up all my work(since its 6 months old and quite a big project) an trying to reinstall bew, node and all others. So I followed the steps like this:

First installed brew:
 `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Then the others:
```  
brew install node
brew install watchman
npm install -g react-native-cli
react-native init AwesomeProject
```  

The simple react native AwesomeProject also doesn't work. I just keep seeing the same error:

``` 
** BUILD FAILED **  

The following commands produced analyzer issues:
        Analyze /Users/nehabhamare/Documents/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp

        Analyze Base/RCTModuleMethod.mm
(2 commands with analyzer issues)

The following build commands failed:
        CompileC build/RCTAnimation.build/Debug-iphonesimulator/RCTAnimation.build/Objects-normal/x86_64/RCTStyleAnimatedNode.o Nodes/RCTStyleAnimatedNode.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist  
```

**Comment by rpmonteiro** [comment]
Exact same issue here.

I've tried
- the third party script thing
- clean ~./rncache
- react-native-git-upgrade
- change project settings

I'm going mad.

**Comment by khadkaPratik** [comment]
These kind are issue are common in some popular packages too 
Thanks React-Native 👍

**Comment by LuchoGil** [comment]
The following build commands failed:
        CompileC /Users/L/Documents/GitHub/helpo/helpo-mobile/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/vlog_is_on.o /Users/L/Documents/GitHub/helpo/helpo-mobile/node_modules/react-native/third-party/glog-0.3.4/src/vlog_is_on.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/L/Documents/GitHub/helpo/helpo-mobile/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/utilities.o /Users/L/Documents/GitHub/helpo/helpo-mobile/node_modules/react-native/third-party/glog-0.3.4/src/utilities.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/helpoMobile.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Help please!!!

**Comment by henryzp** [comment]
@rpmonteiro ，also to me。。。

have you fix it??

**Comment by henryzp** [comment]
my xcode is 10.0

"react-native": "0.55.0"

error message: 

```
** BUILD FAILED **



The following build commands failed:

	CompileC /Users/zhangpu/Documents/imooc_gp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBundleURLProvider.o /Users/zhangpu/Documents/imooc_gp/node_modules/react-native/React/Base/RCTBundleURLProvider.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Installing Build/Products/Debug-iphonesimulator/imooc_gp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier Build/Products/Debug-iphonesimulator/imooc_gp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

anyone can help me?

**Comment by zinopro** [comment]
> Exact same issue here.
> 
> I've tried
> 
> * the third party script thing
> * clean ~./rncache
> * react-native-git-upgrade
> * change project settings
> 
> I'm going mad.

Do you have a special app that can run clean ~./rncache?

**Comment by wanghuajian620** [comment]
![screen shot 2018-11-01 at 4 22 13 pm](https://user-images.githubusercontent.com/31924547/47840887-bbf4b200-ddf2-11e8-89f6-142315170133.png)
What can I do?

**Comment by WimukthiRajapaksha** [comment]
I think the error should be with your internet connection. I think **VPN** is the solution for that issue.

**Comment by dominik-mrugalski** [comment]
> I think the error should be with your internet connection. I think **VPN** is the solution for that issue.

Yup, after reading your answer I noticed that I installed Modify Headers for Google Chrome Plugin. After disable this plugin - errors has gone :)

**Comment by liuqiiiiiii** [comment]
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/a11/Componey/javashop-react_native/ios/build/Build/Intermediates.noindex/RNGooglePlaces.build/Debug-iphonesimulator/RNGooglePlaces.build/Objects-normal/x86_64/NSMutableDictionary+GMSPlace.o /Users/a11/Componey/javashop-react_native/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NeeHow.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

what fuck!
where's the error?
why is error gone?

**Comment by appatappa** [comment]
Is there a clear, simple fix yet? I've upgraded to 0.55.4 and tried everything that @zinopro stated, and the problem still exists.

**Comment by Bonissauro** [comment]
In 0.57 still occurs. And this is just the beggining. Try to figure out the future headache.

**Comment by Bonissauro** [comment]
Everything up-to-date. 

$ node --version
v11.6.0

$ watchman --version
4.9.0

$ npm --version
6.5.0

$ yarn --version
1.12.3

Still not working!

**Comment by renypayus** [comment]
i got the same problem. it's not working and my internet is completely stable

**Comment by Liqiankun** [comment]
* remove `node_modules`
* npm i 
* remove `ios/build/Build`
* react-native run-ios

**Comment by KPS250** [comment]
Any solution for this?

**Comment by andrew-koster-** [comment]
LMAO

**Comment by andrew-koster-** [comment]
No solution, but at least the ticket is closed :D

**Comment by kaushal9678** [comment]
> @kirkstrobeck I am saying that the error is not caused by lock but by the react-native integration with Xcode that seemed to fail for some people. Xcode tooling is kinda brittle when you are doing thing that are not apple way (I learned this the hard way) and the last [comment](https://github.com/facebook/react-native/issues/7308#issuecomment-271857720) mentioned what is wrong and how to fix it.
> 
> Sorry hearing that you pivoted away from Auth0 but the only error where I can see some information is
> 
> ```
> Installing build/Build/Products/Debug-iphonesimulator/awesome.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/awesome.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> ```
> 
> which is what I answered in my unreal response.
> 
> ```
> The following build commands failed:
>   CompileC /Users/kirkstrobeck/awesome/ios/build/Build/Intermediates/A0RNLock.build/Debug-iphonesimulator/A0RNLock.build/Objects-normal/x86_64/A0LockReact.o A0RNLock/Core/A0LockReact.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> ```
> 
> The other line might hide another issue but without the full log, what steps you followed to get that error I can only guess what's wrong.
> 
> @Vikaton @NoahGrumman @krzysztofp if you can provide more information or a sample repo we could debug, that will help.

Just do one thing **Erase all content and settings for simulator and close packager and re-run app by command react-native run-ios.**

<img width="270" alt="Screenshot 2019-07-07 at 9 06 53 AM" src="https://user-images.githubusercontent.com/4991337/60763666-04a5ee80-a097-11e9-9b85-be35f7b1e153.png">
