### ISSUE TITLE
build errors installing and running on ios

### ISSUE THREAD

**Issue by mypark** [auth0/react-native-lock#113]
Starting out with vanilla app using latest react-cli (2.0)

```
react-native init Foo && cd Foo
yarn add react-native-lock
react-native link
react-native run-ios
```

error:
`
The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/Foo.app/PlugIns/FooTests.xctest/FooTests normal x86_64
(1 failure)`

**Comment by hzalaz** [comment]
@mypark Please provide the full log since that error provides no useful info

**Comment by hzalaz** [comment]
Closing this one, if the issue still persists please add more info. Also please check #123 comments
