### ISSUE TITLE
Custom Send code profile image and default country phone code

### ISSUE THREAD

**Issue by vzhen** [auth0/react-native-lock#114]
How to change send code page profile image and country phone code?
I get the country code from user's device then dynamic change the country code in send code page so user don't have to select themselve.
![capture](https://cloud.githubusercontent.com/assets/1941395/22024531/3b4042d6-dd05-11e6-81c4-2a47d6cf454c.PNG)

- [0.4.0 ] Lock version
- [5.1] Android version
- [0.38.0 & ~15.4.0-rc.4 ] React Native & React version
- [ 4.0.2] NPM version

**Comment by hzalaz** [comment]
We have limited support for customizations but merged this PR https://github.com/auth0/react-native-lock/pull/117 for iOS only customization support. The country code is automatically selected from the phone's settings and there is no way to set it up programmatically
