### ISSUE TITLE
Problem when login

### ISSUE THREAD

**Issue by krishbhattacharyya** [auth0/react-native-lock#115]
Hi,
Recently I installed "react-native-lock" in my demo App. But getting an unexpected error while trying to login in facebook.

When I want to login using facebook icon click I got the error just like the shared image. When I try to login with different user I got the same error with the previous user error, when I delete the auth0 record I got the same error with the same user. 

![screenshot_1484916872](https://cloud.githubusercontent.com/assets/10433734/22150594/dfe915c4-df3f-11e6-88d7-86fe4fff386f.png)

**Comment by hzalaz** [comment]
@krishbhattacharyya usually that page has some details about the error, just scroll down and there should be a button `show details` or similar

**Comment by krishbhattacharyya** [comment]
Thanks @hzalaz .
Sorry to late reply.
Yes I have seen yesterday also ( Picture shared bellow).

![screenshot_1484984018](https://cloud.githubusercontent.com/assets/10433734/22172969/9d02cff2-dfda-11e6-994b-ce558b934974.png)

**Comment by hzalaz** [comment]
@krishbhattacharyya would be useful to see the details of the error

**Comment by krishbhattacharyya** [comment]
Thanks now I am going to close this issue.
