### ISSUE TITLE
Build fail with error.

### ISSUE THREAD

**Issue by tiempham** [auth0/react-native-lock#116]
Hi all.
I build a react native v.40 project in xcode 8 and i got a error: 

> ld: warning: directory not found for option '-L/Users/designteam/Library/Developer/Xcode/DerivedData/lock-eoldhqeagupjtqdylrwaoqqaleet/Build/Products/Release-iphonesimulator/AFNetworking'
ld: warning: directory not found for option '-L/Users/designteam/Library/Developer/Xcode/DerivedData/lock-eoldhqeagupjtqdylrwaoqqaleet/Build/Products/Release-iphonesimulator/Lock'
ld: warning: directory not found for option '-L/Users/designteam/Library/Developer/Xcode/DerivedData/lock-eoldhqeagupjtqdylrwaoqqaleet/Build/Products/Release-iphonesimulator/Masonry'
ld: warning: directory not found for option '-L/Users/designteam/Library/Developer/Xcode/DerivedData/lock-eoldhqeagupjtqdylrwaoqqaleet/Build/Products/Release-iphonesimulator/SimpleKeychain'
ld: warning: directory not found for option '-L/Users/designteam/Library/Developer/Xcode/DerivedData/lock-eoldhqeagupjtqdylrwaoqqaleet/Build/Products/Release-iphonesimulator/TouchIDAuth'
ld: warning: directory not found for option '-F/Users/designteam/Library/Developer/Xcode/DerivedData/lock-eoldhqeagupjtqdylrwaoqqaleet/Build/Products/Release-iphonesimulator/Lock'
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I checked some issuses with same error with me but.. Anyone can help me? Thanks.

**Comment by julienroussel** [comment]
I had the same issue. I resolved it with

1. Add `Pods.xcodeproj` in XCode (drag&drop from finder after `open ios/Pods`)

![capture d ecran 2017-01-26 a 17 37 57](https://cloud.githubusercontent.com/assets/1136972/22340756/d0922eea-e3ee-11e6-8eac-c9114c35e8e9.png)

2. Then I had `Undefined symbols` issue, resolved by following https://github.com/facebook/react-native/issues/8880#issuecomment-236994554

3. Finally, I had issue with the test project too. I Added `-lc++` to `Other linker flags` in the test target.

Hope this will work for you!

**Comment by drdeath113** [comment]
Thank @julienroussel for your reply! I will try later hope it work.
