### ISSUE TITLE
Lost Callback

### ISSUE THREAD

**Issue by mickr** [auth0/react-native-lock#118]
Hi, seem to have an issue when reloading the lock screen the auth callback never gets called.

```
import Auth0Lock from 'react-native-lock';
import { AsyncStorage } from 'react-native'
import { isTokenExpired } from './jwtHelper';

export default class AuthService {
  constructor(clientId, domain) {
    this.clientId = clientId;
    this.domain = domain;
    this.lock = new Auth0Lock({ clientId, domain });

    this.showLock = this.showLock.bind(this);
  }

  showLock(callback) {
    this.lock.show({}, (err, profile, token) => {
      AuthService.setToken(token.idToken);
      callback(token.idToken);
    });
  }
```
When calling showLock the first time and if I log in, everything works. If I reload, then reload again on the  lock screen, the callback no longer will fire. Any ideas?

**Comment by mickr** [comment]
After dealing with this for sometime, I'm not sure if there is a case where there would be a reload of the lock screen on a device.

**Comment by hzalaz** [comment]
Its odd but it could be if you login from the Lock displayed before the reload since the JS context is recreated and hence your old callback is no more there. Lock for now is a wrapper around the native libs so it has no knowledge of RN lifecycle
