### ISSUE TITLE
Is there a hide method or a way to know if the modal is visible?

### ISSUE THREAD

**Issue by mypark** [auth0/react-native-lock#125]
I need to hide the lock screen if the user state ever changes to authenticated by other means.

1. Is there a way to detect whether the lock modal is open?
2. How do I hide the modal - I tried calling lock.hide() but I get an error `Auth0LockModule must not be null`

**Comment by hzalaz** [comment]
Currently there is no method to do it since it will rely on browsing the ios view hierarchy or android activities in the current task. We are not planning to add this for this version but rather focus on implementing lock in react-native JS
