### ISSUE TITLE
No resource found that matches @style/Lock.Theme

### ISSUE THREAD

**Issue by ldunphy1** [auth0/react-native-lock#129]
from package.json:
"dependencies": {
    "react": "15.3.2",
    "react-native": "0.34.1",
    "react-native-collapsible": "^0.7.0",
    "react-native-custom-checkbox": "^1.5.0",
    "react-native-datepicker": "^1.4.2",
    "react-native-elements": "^0.6.4",
    "react-native-lock": "^0.5.0",
    "react-native-material-kit": "^0.3.3",
    "react-native-toggle": "^1.0.3",
    "react-native-vector-icons": "^3.0.0"
  }
npm version 4.2.0

![untitled](https://cloud.githubusercontent.com/assets/22159844/23346051/d06e1242-fc64-11e6-8466-a9af5f7cfdde.png)

**Comment by Compulsed** [comment]
I am getting this same error with 

```
  "dependencies": {
    "react": "~15.4.1",
    "react-native": "0.42.0",
    "react-native-cli": "^2.0.1",
    "react-native-config": "^0.3.1",
    "react-native-lock": "^0.5.0"
  }
```

**Comment by hzalaz** [comment]
@ldunphy1 so did you follow the next steps in the install guide? what is in the `AndroidManifest.xml` that fails?

**Comment by ldunphy1** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.dirtydrawz"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      
    <activity
    android:name="com.auth0.lock.LockActivity"
    android:theme="@style/Lock.Theme"
    android:screenOrientation="portrait"
    android:launchMode="singleTask">
    </activity>
    
    
    <activity
        android:name="com.auth0.identity.web.WebViewActivity"
        android:theme="@style/Lock.Theme">
    </activity>
    
    
    <activity
        android:name="com.auth0.lock.passwordless.LockPasswordlessActivity"
        android:theme="@style/Lock.Theme"
        android:screenOrientation="portrait"
        android:launchMode="singleTask">
    </activity>
    <activity
        android:name="com.auth0.lock.passwordless.CountryCodeActivity"
        android:theme="@style/Lock.Theme">
    </activity>
    
    </application>

</manifest>

**Comment by ldunphy1** [comment]
Sorry, I had done these steps so many times to try and get this to work...I must have forgotten to do that part this time.  But I reverted all my changes and started over and followed every step in the installation guide.

**Comment by hzalaz** [comment]
@ldunphy1 so it is still failing?

**Comment by ldunphy1** [comment]
Only thing different I did was remove rnpm pre-script and post-script lines from react-native-lock/package.json...which I believe you had told me to do in another issue I commented on.

Yes, it's failing and outputting the same errors as above when I opened the issue.

**Comment by hzalaz** [comment]
Its working for me and your AndroidManifest.xml looks ok.
 I'd make sure that the android sdk is up to date https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment and try again

**Comment by ldunphy1** [comment]
![image](https://cloud.githubusercontent.com/assets/22159844/23876712/21aeb4e8-0815-11e7-8e9e-9a20095caf09.png)

**Comment by ldunphy1** [comment]
![image](https://cloud.githubusercontent.com/assets/22159844/23876741/41aa999c-0815-11e7-8a13-dba34002d9ed.png)

**Comment by ldunphy1** [comment]
I just updated the Google APIs Intel x86 Atom_64 System Image so my sdk packages and tools match exactly.  It's still not working.

**Comment by tjaartvdwalt** [comment]
I got a similar error. Here is what solved it for me:

I read [the docs](https://auth0.com/docs/quickstart/native/react-native-android), but missed the step:
`rnpm link react-native-lock`.

For what it is worth the documentation is out of date. `rnpm` is now deprecated, as you use `react-native-cli` for linking. The correct command is:

`react-native link react-native-lock`

This solved my issue.

**Comment by atmortensen** [comment]
I'm getting the same error.

`:app:processDebugResources
C:\Users\alext\Documents\web-dev\Instasham-app\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:41:28-45: AAPT: No resource found that matches the given name (at 'theme' with value '@style/Lock.Theme').

C:\Users\alext\Documents\web-dev\Instasham-app\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:47:28-45: AAPT: No resource found that matches the given name (at 'theme' with value '@style/Lock.Theme').

C:\Users\alext\Documents\web-dev\Instasham-app\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:55:28-45: AAPT: No resource found that matches the given name (at 'theme' with value '@style/Lock.Theme').

C:\Users\alext\Documents\web-dev\Instasham-app\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:59:28-45: AAPT: No resource found that matches the given name (at 'theme' with value '@style/Lock.Theme').

C:\Users\alext\Documents\web-dev\Instasham-app\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:37: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Lock.Theme').

C:\Users\alext\Documents\web-dev\Instasham-app\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:45: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Lock.Theme').

C:\Users\alext\Documents\web-dev\Instasham-app\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:51: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Lock.Theme').

C:\Users\alext\Documents\web-dev\Instasham-app\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:57: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Lock.Theme').


:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.429 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
`

**Comment by nicolasgere** [comment]
same error for me, did you found a fix?
