### ISSUE TITLE
Cannot read property of 'init' of undefined

### ISSUE THREAD

**Issue by ldunphy1** [auth0/react-native-lock#133]
I saw that this issue existed, but also that it was closed without stating a solution.  
My package.json:
{
  "name": "dirtydrawz",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.3.2",
    "react-native": "0.34.1",
    "react-native-collapsible": "^0.7.0",
    "react-native-custom-checkbox": "^1.5.0",
    "react-native-datepicker": "^1.4.2",
    "react-native-elements": "^0.6.4",
    "react-native-lock": "^0.5.0",
    "react-native-material-kit": "^0.3.3",
    "react-native-toggle": "^1.0.3",
    "react-native-vector-icons": "^3.0.0"
  }
}

![image](https://cloud.githubusercontent.com/assets/22159844/23816124/19114778-05b9-11e7-85c1-51d993fdb837.png)

**Comment by lukecwilliams** [comment]
Here's how I solved this.  Note that it appears the react-native linking through the CLI is not working correctly.

You can see better error messages by first running react-native run-ios.  If you have the same problem as I do, you'll see that Lock.h and OneSignal.h are not found.

1. Change all paths in xcode > Project > Libraries > A0RNLock.xcodeproj > Build Settings > All > Search Paths > Header Search Paths to the ones specified in the Manual install section of the RN Lock instructions.  (this requires removing one layer of ".." from each line)

2. Do the same for Libraries > RCTOneSignal.xcodeproj

3. `yarn add react-native-onesignal` (or do it with npm).  (

4. Add this line to your podfile (per https://github.com/geektimecoil/react-native-onesignal/issues/59)

`pod 'OneSignal' `

5. Clean with xcode

6. `react-native run-ios`

**Auth0 devs: please fix the automated installer!**

**Comment by ldunphy1** [comment]
@lukecwilliams I'm actually running an android project.  Do you have any solutions for android?

**Comment by hzalaz** [comment]
@lukecwilliams the automated installer works for iOS in the latest version also in your instructions the change in the Podfile (OneSignal) is not needed since you never perform a `pod install` so the Xcode project is not affected. 

The only way the automated install fails if you changed something in Xcode project by hand

**Comment by ldunphy1** [comment]
@hzalaz any solutions for my issue?

**Comment by hzalaz** [comment]
About the android error make sure the plugin is properly linked for android which includes it being included like stated in https://github.com/auth0/Mobile-Samples.React/issues/11#issuecomment-281495729 because that error means that react native could not find the native module.

**Comment by hzalaz** [comment]
@ldunphy1 last week tried the install from scratch (using react-native cli project creator) and it worked without issues in both platforms (tested on Mac not sure that matters)

**Comment by ldunphy1** [comment]
my MainApplication.java:
package com.dirtydrawz;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}

**Comment by ldunphy1** [comment]
I don't have a Mac.  I have Windows.

**Comment by lukecwilliams** [comment]
@hernan-m87 Thanks for the response.  Good to know 'OneSignal' is unnecessary to add.

The automated installer definitely added the two new libraries with an extra "../" in each header path that I had to manually remove.

**Comment by ldunphy1** [comment]
I tried on a friends computer (also windows os), to make sure it's not just my machine.  It also wasn't working

**Comment by hzalaz** [comment]
@ldunphy1 did perform the first step of https://github.com/auth0/react-native-lock#react-native-cli-1 ?

**Comment by ldunphy1** [comment]
Now I'm back to this issue that was never answered: https://github.com/auth0/react-native-lock/issues/129

**Comment by StevenFrostwick** [comment]
Just in case any one else comes along:

I was also getting these errors (missing Lock/Lock.h etc.) and had to change the Header Search Paths to

```
$(SRCROOT)/../../React
$(SRCROOT)/../../react-native/React
${SRCROOT}/../../../ios/Pods/Headers/Public
${SRCROOT}/../../../ios/Pods/Headers/Public/Lock
```

BTW I was getting these errors whether I followed the **react-native-cli** or **Manual** instructions.

**Comment by lukecwilliams** [comment]
@StevenFrostwick My working first line there has 3 "directory up" commands, does yours work with just 2?

I have:
```$(SRCROOT)/../../../React

Rest are the same.

**Comment by StevenFrostwick** [comment]
Yeah three `../`

Which seems to make sense as React is two levels up from the `A0RNLock.xcodeproj` file.

**Comment by smooJitter** [comment]
Can I confirm, if I install manually, do I still need a pod file?
