### ISSUE TITLE
keep the user logged in

### ISSUE THREAD

**Issue by AbdulrhmanBagazi** [auth0/react-native-lock#137]
I'm testing the auth0 on emulator for my app each time I refresh I have to log in again, is there is an easy way to make the user logged in even if he close the app or refresh

**Comment by mattgittings** [comment]
Did you find a good solution for this? Also it would be nice to have the users credentials save so they are automatically signed in when they open the app.

**Comment by hzalaz** [comment]
You need to store the tokens yourself and handle the login state in your app, Lock provides no way of doing this now. Ideally you should store the tokens in a secure storage like iOS Keychain, also there is AsyncStore of RN but the token will be stored in plain text (in the app sandbox though).
