### ISSUE TITLE
Arrays with Objects in User/AppMetadata not being parsed on Android

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/react-native-lock#138]
`user_metadata` and `app_metadata` are not available with the current `UserProfileBridge` implementation. ~Instead of using the `getExtraInfo()` method and [getting them](https://github.com/auth0/react-native-lock/blob/24990c62efaa5b88aa0ec372da4fa506344db49d/android/src/main/java/com/auth0/lock/react/bridge/UserProfileBridge.java#L75-L77) from that map, it should use the [specific getters](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/result/UserProfile.java#L116-L122) `getUserMetadata()` and `getAppMetadata()`.~

Edit: This library is using lock.android v1 so the above suggestion is not valid.

### Steps to reproduce:
1. Clone this repo. 
1. Add your auth0 credentials to the `app-sample` project.
1. Run the app in an Android emulator/device and log in with any credentials, i.e. using database username/password.
1. The `profile` received in the call does contain the `app_metadata` and `user_metadata` properties, but if there is an array with OBJECTS, they are not converted and the array appears as empty.

this metadata:
```json
"user_metadata": {
		"assignments": [
                 "text",
                 {
			"name": "object1"
		}, {
			"name": "object2"
		}]
	}
```

it's converted to this:
```json
"user_metadata": {
		"assignments": [
                     "text"
                ]
	}
```

If you now press the "greet" button, the received token (after calling /userinfo) it's converted fine, and the `user_metadata` contains all the original values.

**Comment by cstoddart** [comment]
Hello, has this been fixed yet? I really need to access app_metadata..

**Comment by lbalmaceda** [comment]
Hi @cstoddart 
The fix I suggested is invalid as this library is not using v2 but rather v1 of lock.android. However, I was able to reproduce it and noticed that it was happening only for Objects contained inside an Array. 

The issue is still in the `UserProfileBridge`. As you can see in [this line](https://github.com/auth0/react-native-lock/blob/master/android/src/main/java/com/auth0/lock/react/bridge/UserProfileBridge.java#L133) it's missing the `Map` type handling. I've added the check like this:

```java
if (item instanceof Map) {
    //noinspection unchecked
    push((Map) item, array);
}
```

And added the `push` method to add a Map to the array:

```java
    private void push(Map<String, Object> map, WritableArray into){
        if (map == null || map.isEmpty()) {
            //Maybe this is not necessary. 
            return;
        }
        final WritableMap writableMap = Arguments.createMap();
        for (Map.Entry<String, Object> entry: map.entrySet()) {
            put(entry.getKey(), entry.getValue(), writableMap);
        }
        into.pushMap(writableMap);
    }
```

This fixes the issue. cc @hzalaz 
Cheers,

**Comment by cstoddart** [comment]
@lbalmaceda You are a wizard!! It works! Thank you so much!
