### ISSUE TITLE
Add refreshToken method

### ISSUE THREAD

**Issue by CKarper** [auth0/react-native-lock#15]
How do I use the refresh token provided by the ```show()``` callback?

each time my app is restarted it requires the user to re-login.  Maybe it's obvious, but I've definitely missed it.  Thanks!

**Comment by hzalaz** [comment]
@CKarper here is a guide explaining what to do platform agnostic https://auth0.com/docs/refresh-token. Basically you need to call `/delegation` with the refresh token when your id_token expires. I don't have a code example on how to perform the request but it should be easy enough to do it with fetch API.

**Comment by CKarper** [comment]
So RN Lock doesn't expose a method for this?  The bottom of this article says that libraries such as Lock have support for refreshing the tokens, so I was expecting it to be "baked in".  Thanks for the quick  reply...

**Comment by CKarper** [comment]
As per: https://auth0.com/docs/libraries/lock/using-a-refresh-token

**Comment by hzalaz** [comment]
Also I have a pending PR #13  for this, once I finish some other stuff I'll release it

**Comment by CKarper** [comment]
Is that the same as a refreshToken?  I'm relatively new, bu I was expecting that to be the method for accessing tokens for delegated third party integrations.  Will it do double duty?

**Comment by hzalaz** [comment]
@CKarper yes, but this case it's not a third party but auth0 itself. I'll probably change the method name in js to make it clear is `delegation` operation instead of get a delegation token.

**Comment by julesbou** [comment]
The only way I've found to persist user sessions is to store `profile.user_id` with `AsyncStorage`, when application starts if the `user_id` is not null, I skip lock. To logout, I erase `user_id` key in `AsyncStorage`. Indeed, it's very hackish. So If there's a better way and It's working, I'm all ears.

**Comment by hzalaz** [comment]
@julesbou maybe it's better to store the id_token, it already has the `user_id` in the claim `sub` and also has an expiration if you wish to make your users to authenticate again. You can check the structure of the `id_token` in [jwt.io](http://jwt.io)

**Comment by hzalaz** [comment]
Closing this one, It's missing on Android but there is an issue for it #31

**Comment by avishayil** [comment]
Can someone give a code example on how to show the lock screen only when the user is not logged in?
Struggling with this...
Each time user entering the app he has to log in, nothing remembers that he is logged in.

**Comment by stantoncbradley** [comment]
@avishayil you need to store login information (ie isLoggedIn, profile, token) in your app, and then check whether the user is logged in before calling lock.  if you want to persist react native data between app sessions check out react native async storage (or redux persist if using redux)

**Comment by mypark** [comment]
How would you check for token expiration first before calling refresh - or would you just call refresh on every app start?  Should we be checking for an expired token error or do we get the token expiration date from the token itself somehow?
