### ISSUE TITLE
Can Lock be updated to work with Expo? (non-native module)

### ISSUE THREAD

**Issue by lukecwilliams** [auth0/react-native-lock#154]
We're porting our code over to Expo and would like to keep using Auth0.  Trying to access react-native-lock in Expo yields an error because LockModule is native, and Expo disallows native code.

Superficially, it seems that this could be done non-natively - pull up a UI, redirect to a web URL if necessary, call back to app.  

Expo is getting a lot of traction - can an Expo-compatible version be made, or can you explain the limitations of why not?

(The complete web-based interface provided in expo/auth0-example isn't suitable for a production app.)

Thank you!

**Comment by lukecwilliams** [comment]
Never mind - after working to port our app to Expo for a few days, we're going back to vanilla React Native.  Too many obscure issues getting Relay, Auth0, TypeScript running, and not being able to run native code (like auth0 Lock) is looking like too big of a limitation.

**Comment by dmk255** [comment]
I'd like to throw in my 2 cents for getting this working with Expo. It's fantastic for development and projects like [create-react-native-app](https://github.com/react-community/create-react-native-app) have adopted it too.

At present, I've basically just made my own login button that pulls up the browser in expo based on https://github.com/expo/auth0-example .

**Comment by hzalaz** [comment]
@dmk255 afaik expo does not allow libraries to use the native sdks (NativeModules) and this is needed for us to perform operation like opening the correct system browser and accessing the crypto api of the phone. This Lock is 100% written in native code, our [SDK](https://github.com/auth0/react-native-auth0) has some native code for the reasons I mention before. We could write a bridge to show the browser inapp the expo way (we are not eager to tie us to a specific fwk but we can evaluate) but I don't sure about the crypto api since I'd rather use the native ones over a JS implementation.

**Comment by hzalaz** [comment]
Also if you are willing to write a sample so we can add it to our list just contact us via https://support.auth0.com

**Comment by dmk255** [comment]
Thanks for the quick response @hzalaz! I think adding a bridge is a good investment as it would significantly reduce the barrier to entry for new react native apps. 

In regards to the sample app what specifically are you looking for? My current project effectively just reimplements the expo auth0-example in the repo above.

**Comment by hzalaz** [comment]
Maybe something similar to the vanilla react-native https://github.com/auth0-samples/auth0-react-native-sample but with Expo (you won't be able to use the our sdk though)

**Comment by dmk255** [comment]
I just took a look through that functionality and it looks like the preexisting https://github.com/expo/auth0-example replicates it almost exactly. I can make an example which is similar but it would still use the web browser in the same way.  I'm happy to chat more off of this issue - is there an Auth0 slack team ( or something similar ) I can jump on?

**Comment by hzalaz** [comment]
Ok, let me discuss internally and I can ping you if needed. Sadly we don't have a public slack

**Comment by dan-kez** [comment]
Hi @hzalaz - just wanted to check in and see if there are any updates on this.

**Comment by lukewlms** [comment]
@dmk255 FYI, unfortunately react-native-lock is deprecated now in favor of react-native-auth0 which offers only web-based authentication.
