### ISSUE TITLE
Google login not allowed

### ISSUE THREAD

**Issue by ylac** [auth0/react-native-lock#157]
Hi, I'm getting a "Error: disallowed_useragent" message for Google login/signups. It says the user-agent is not allowed to make an 0Auth authorisation request as it is classified as an embedded user-agent (also known as a web-view). I'm on iOS react-native 0.43.3.

Does this mean Google logins are no longer allowed?

**Comment by lukecwilliams** [comment]
Google logins are allowed by upgrading to 0.6.0, and setting the useBrowser flag.  See [this section in the Readme](https://github.com/auth0/react-native-lock#avoid-webview-for-social-auth).

Google does not allow in-app web view logins anymore; they must be done through an external browser like Safari for security and usability reasons.

**Comment by ylac** [comment]
Thanks for that, all good after adding the callback URL in Auth0 per: https://github.com/auth0/react-native-lock/pull/155
