### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by raphaeltm** [auth0/react-native-lock#160]
As per the instructions, I run `npm install --save react-native-lock`. I then try `react-native link react-native-lock` but get this error:
```
rnpm-install ERR! Something went wrong while linking. Error: spawn UNKNOWN 
```
I went digging through GitHub to see if anybody else had a similar error, and I found [this](https://github.com/facebook/react-native/issues/9489) which suggests it might be on the Auth0 side? Apparently it was previously an error that was fixed... but no word on where/how it was fixed.

React Native Lock 0.6.0
Android Version 6.0
React Native 0.44.2
NPM 5.0.0
Windows 10

**Comment by raphaeltm** [comment]
Aha. I didn't see it in my first searches, but I guess the answer is [here](https://github.com/facebook/react-native/issues/9489) and I guess Auth0 isn't super interested in making this work for Windows.

**Comment by raphaeltm** [comment]
I've already committed to Auth0 for a project... so I went out and bought a Mac... *sigh*

**Comment by hzalaz** [comment]
@raphaeltm tbh we haven't had time to take a look at it and can't think of a safe way to detect in the preinstall scripts what OS I am at besides wrapping them in JS files and checking the OS there. If you are willing to send a PR I might check it out.

Also if you are planning on building an iOS app you would need a Mac even if you don't use Auth0.

**Comment by raphaeltm** [comment]
@hzalaz makes sense.

I was planning on focusing on Android, and then adding iOS support later on with a Mac Mini that's not super convenient for me to make use of. But I seem to regularly run into things where tools and libraries are focused on iOS, and OSX-based development... So I decided it might be time to just get it over with and go out and grab a Apple laptop for any of those situations.

I'll see if there's something I can do, but in the meantime, I'll probably just stick to the newfound convenience of relying on all the Apple-focused stuff out there 😛 

Thanks for the quick response, though! 😄
