### ISSUE TITLE
Is there anyway to avoid the Auth0 sign-in fields? 

### ISSUE THREAD

**Issue by IgnacioAbadie** [auth0/react-native-lock#163]
Hello all, I am using react-native-lock to connect with google through Auth0, but i can't find the way to avoid the "auth0" login view.

I want one of two things:

Avoid the auth0 sign in view to pass directly to Google sign in

or at least remove the Auth0 sign in fields.

![screen shot 2017-06-05 at 2 31 25 pm](https://cloud.githubusercontent.com/assets/24418053/26795442/09d620d0-49fc-11e7-892c-7efa9bff59d0.png)

**Comment by hzalaz** [comment]
@IgnacioAbadie don't use this library and use https://github.com/auth0/react-native-auth0#webauth, specifying `connection` parameter `google-oauth2`.
