### ISSUE TITLE
Linkedin no "cancel" / "allow" button displayed

### ISSUE THREAD

**Issue by alexandrzavalii** [auth0/react-native-lock#166]
I used the react-native template from auth0 .
And when I run it in simulator I have the authorization without buttons allow/cancel

![ezgif com-resize](https://user-images.githubusercontent.com/10633451/27002145-38ac555e-4dd1-11e7-8ada-718a7be911d1.gif)

**Comment by hzalaz** [comment]
That is out of Lock control since its Linkedin login page and they decide how its shown and what actions can be done. (Also you have the cancel top-left from the webview lock uses)

**Comment by alexandrzavalii** [comment]
@hzalaz
there was no any buttons, so I was not able to sign in at all.

But its because I forgot to specify in auth0 settings the right callback for linkedin.
My bad
