### ISSUE TITLE
How to set device name? 

### ISSUE THREAD

**Issue by NetPumi2** [auth0/react-native-lock#176]
I try to set the name of the device what user connect to auth0. I use webAuth in a react-native and native module with lock for Android. And I have no idea how to send the name of the device to auth0. This is my try (RN) but does't work:

```
const options = {
  auth: {
    params: {
      device: "UUID_DEVICE_NAME"
    },
    device: "UUID_DEVICE_NAME"

  }
};
const auth0 = new Auth0(
  auth0Config, options
);
```
And i need some thing for `Lock.Android`

**Comment by lbalmaceda** [comment]
If you need to send extra parameters in the authentication call then I suggest you look into `authParams` like the [readme](https://github.com/auth0/react-native-lock#lock) says. If you're using the lock.android you can achieve the same by calling this method https://github.com/auth0/Lock.Android/blob/master/lib/src/main/java/com/auth0/android/lock/Lock.java#L295

**EDIT:** Now that you've clarified the question in the [other repo](https://github.com/auth0/Lock.Android/issues/436#issuecomment-326003085), the answer should be that the `device` parameter is no longer accepted when asking for refresh_tokens. The name is taken from the user-agent header, so you might want to look into that. Anyway, the only reason why you would like to name the devices is to easily revoke tokens. But to do that now you can just pass the token and the client_id as explained [here](https://auth0.com/docs/tokens/refresh-token/current#revoke-a-refresh-token).
