### ISSUE TITLE
Auth0Lock.show - Cannot read property 'init' of defined 

### ISSUE THREAD

**Issue by slayrbear** [auth0/react-native-lock#20]
I followed the instructions for the React-Native Auth0 sample project and am getting this error below when pressing the Show Lock button (_onShowLock function). Am I missing a configuration in xcode/xcworkspace?

![screenshot 2016-03-30 19 05 28](https://cloud.githubusercontent.com/assets/191961/14163463/a6c7fa68-f6aa-11e5-88bc-bf9d798ece3c.png)

**Comment by hzalaz** [comment]
@slayrbear please try it with the module `react-native-lock` (instructions in this project README), seems the iOS native module cannot be found.

**Comment by narek11** [comment]
@hzalaz I am getting the same screen on genymotion android.
Any clue what causes this ?
I am following https://auth0.com/docs/quickstart/native/react-native-android tutorial.

**Comment by narek11** [comment]
not sure what was going on with genymotion but all of a sudden it started to work.

**Comment by ldunphy1** [comment]
I am getting the same error.  Any solutions?

**Comment by StephenGilboy** [comment]
I was able to get this working on ios by deleting my app from the iPhone simulation then running `react-native run-ios` again.
