### ISSUE TITLE
Add custom login option

### ISSUE THREAD

**Issue by mmelchio** [auth0/react-native-lock#30]
How do I add a custom login button from a generic OAuth1 connection in my React Native Android app?

**Comment by hzalaz** [comment]
@mmelchio If you mean a custom OAuth2 connection, once we make the iOS & Android library handle it will show up in Lock as any other social connection (e.g. facebook).

If you want to add another button to the UI, or change the layout of Lock, you won't be able since there is no support for it yet.

**Comment by mmelchio** [comment]
@hzalaz Thanks for your reply. OAuth1. 
I know that the dashboard only allows me to add OAuth2 connections. But I asked the support and they just sent me the links to the docs for generic OAuth1 connections. So I assumed that it would be possible to add OAuth1 providers.
Seems like it is not possible.
That would be a nice feature. Also if the docs would be more specified for the used technologies (for example React Native in this case).

**Comment by hzalaz** [comment]
@mmelchio it's not tailored for react native since it's not available right now :). If you can request it (or anything you need in the future) [here](http://feedback.auth0.com)

**Comment by hzalaz** [comment]
For OAuth1 support in react native

**Comment by mmelchio** [comment]
Ok, thank you

**Comment by esdrasportillo** [comment]
Hi, you think the lock for react-native will support custom layouts soon? It would be awesome...
