### ISSUE TITLE
Callback not firing

### ISSUE THREAD

**Issue by mickr** [auth0/react-native-lock#32]
I have ran into the issue of the `lock.show()` callback not firing on the first authentication attempt. The screen slides down and I am presented with a white screen, if I reload my simulator it will show the lock screen again and if I re-auth the call back will fire. 

Any ideas?

**Comment by hzalaz** [comment]
@mickr Can you provide a little more info? in what platform you are trying this? just user-pass?. If you have a sample that can reproduce the issue it will be helpful

**Comment by mickr** [comment]
Sure, I am using it with iOS and using social auth (Facebook). I am using Altjs actions to but have experienced the issue outside of Alt as well.

```javascript
render() {
        if (this.props.user.loggedIn) {
            return (
                <View style={styles.container}>
                    <TabBar handlePress={AppActions.selected}
                            selected={this.props.app.selected}
                            macros={this.props.macros}
                            user={this.props.user} />
                </View>
            );
        } else {
            return (
                <View>
                    {UserActions.showLock()}
                </View>
            )
        }
    }
```

**Comment by hzalaz** [comment]
@mickr did you follow these [steps](https://auth0.com/docs/quickstart/native-mobile/react-native-ios/no-api#optional-twitter-facebook-native-login) if you are using native integrations?

**Comment by mickr** [comment]
Oh no 😑

**Comment by mickr** [comment]
I followed the listed instructions in the docs and everything seems to be going great and Safari gets called to allow for authorization. When I authorize, I get an error when logging in. Do I need to configure a specific callback in the Auth0 dashboard for React Native?

<img width="373" alt="screen shot 2016-04-26 at 11 26 13 pm" src="https://cloud.githubusercontent.com/assets/7842095/14843584/59e16592-0c06-11e6-90bf-0a975d68c28e.png">

**Comment by bennythomps** [comment]
@hzalaz I'm using Google and experiencing the same behavior, first call does nothing. I don't see anything in the linked instructions for Google, so I'm at a loss.

**Comment by hzalaz** [comment]
@bennythomps those steps apply to Google too. In the case for Google in iOS, I'd recommend avoiding the "native" login since, last time I checked, it will always use web-based login.
