### ISSUE TITLE
Lock doesn't work with use_frameworks flag

### ISSUE THREAD

**Issue by chirag04** [auth0/react-native-lock#34]
Seems like Xcode cannot find `<Lock/A0Lock.h` file not found.

**Comment by hzalaz** [comment]
Could you provide a little more info?, like what version of cocoapods you are using, Xcode version, and probably react-native version

**Comment by chirag04** [comment]
```
use_frameworks!

target 'qsi' do
source 'https://github.com/CocoaPods/Specs.git'

pod 'Lock'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'

end
```


thats my podfile. Do you think ```use_frameworks!``` is breaking it?

**Comment by chirag04** [comment]
yeah `use frameworks` breaks it. i just removed it.

**Comment by hzalaz** [comment]
@chirag04 thanks, now I know why it breaks. That flag won't be of much use now so you can safely remove it but I'll patch the lib

**Comment by hzalaz** [comment]
Closing this for the time being, there is a workaround in the README
