### ISSUE TITLE
Issue with Dynamic Frameworks and cocoaPods

### ISSUE THREAD

**Issue by nico75005** [auth0/react-native-lock#38]
> Also make sure you are not adding use_frameworks! in your Podfile, there is a known issue with Dynamic Frameworks that needs to be fixed.

Is it an issue with CocoaPods or Lock?
Because if I'm not wrong, you need to use `use_frameworks!` with Swift pods.
Then how can I do?

Here is what I get when I uncomment `use_frameworks!`

![screenshot 2016-05-09 12 47 43](https://cloud.githubusercontent.com/assets/1647328/15101431/4b7b19a2-15e4-11e6-91a6-88a8ad4a7074.png)

**Comment by hzalaz** [comment]
This library is not written in swift so the flag is not needed for Lock, so you can safely remove it. We'll patch the library (see #34).

**Comment by nico75005** [comment]
Any ETA? Because we need to use Swift libraries and this is blocking us.

**Comment by hzalaz** [comment]
EOW, I wanted to add more things but if I can't I'll release this and what I have on Friday

**Comment by nico75005** [comment]
Thanks.

**Comment by nico75005** [comment]
Any news on the release?

**Comment by hzalaz** [comment]
No luck making it work with as a swift fwk since I can't make it find Lock lib headers from CP.

**Comment by triage** [comment]
thank you for your work on auth0.
this is indeed blocking for me, too.
what are our options at this point?
thank you.

**Comment by hzalaz** [comment]
@triage try doing this https://github.com/auth0/react-native-lock/blob/master/README.md#cocoapods-with-uses_framework-flag. It's a workaround till we figure out a better way (or hope for react-native to be included to a project in a better way).
