### ISSUE TITLE
Closable not working on Android

### ISSUE THREAD

**Issue by changchup** [auth0/react-native-lock#41]
Good Morning Auth0,

I am using the closable option on IOS without any issues however on Android the "X" in the top left hand corner does not appear, so the user has to login to get exit the Auth0 screen.

    lock.show({
      closable:true,
      }, (err, profile, token) => {

**Comment by nikolaseu** [comment]
Hi @changchup, the closable option in Android doesn't add an "x", it just lets the user go back in a "standard Android way", with the back button.

**Comment by changchup** [comment]
Good, thank you!  

Silly me.
