### ISSUE TITLE
LinkedIn implementation

### ISSUE THREAD

**Issue by isaacvigil** [auth0/react-native-lock#42]
Hello,
when implementing oAuth (for LinkedIn) inside a React Native WebView Component, Once successfully logged in and the uri-redirect is initiated, how do I trigger and pass the token back into the non-WebView React Native Component or store it asyncStorage for future use. Either using Promises, async/await or any alternative method of delivery.
Thank you.

**Comment by tomav** [comment]
Same question here...

**Comment by isaacvigil** [comment]
Tomav, this is the answer we got:

Hi,

When you call the authorize on the simpleauth client it returns a Promise that, if the authentication is successful, resolves with an object that contains the token and some other user info

simpleAuthClient.authorize('linkedin-web').then((info) => {
  let token = info.token;
  // Store the token somewhere
})

We fixed the issue using Cocoapods, hope is useful.
Cheers.

**Comment by hzalaz** [comment]
@isaacvigil not sure I understand the question or its about this library. Currently you can authenticate using linkedin without Lock by doing:

```js
var lock = // Initialise Lock with your Auth0 credentials
lock.authenticate("linkedin", {}, (error, profile, token) => {
  // Authenticated with token & profile or an error
});
```

This currently works in iOS only since we haven't bridged it for Lock Android.

Not sure this helps @tomav

**Comment by tomav** [comment]
Yes, my question was more general, getting information from the WebView as explained in the initial post of this issue.

**Comment by tiempham** [comment]
Hi @hzalaz. Is lock.authenticate() support for Android now? Thanks You.
