### ISSUE TITLE
How to get id token after logged in ????

### ISSUE THREAD

**Issue by devux** [auth0/react-native-lock#47]
Hello all,

I can able to login by using this code

    lock.show({}, () => {
    });

but I need id_token for further authentication I tried with this 

    lock.show({}, (err, profile, token) => {
      console.log(token);
      console.log('Logged in!');
    });

but it showing err,profile and token is undefined.
Could anybody please help in this scenario?

**Comment by hzalaz** [comment]
@devux what version of `react-native-lock` are you using?
have you tried with our [sample application](https://auth0.com/docs/quickstart/native-mobile/react-native-ios/no-api)?

**Comment by Maxyss** [comment]
@devux have you resolved this?

**Comment by allpwrfulroot** [comment]
See if any of this helps; note that it's for linkedin signin only and you might have to modify the Auth0 application through your Auth0 dashboard AND your lock.show({ connections: , etc })  to accommodate other signin methods.

````js
import Auth0Lock from 'react-native-lock';

var lock = new Auth0Lock({
  clientId: 'supercalifragalisticexpialidocious',
  domain: 'xxxxxxxxxx.auth0.com'
});

class Login extends Component {
  constructor(props){
    super(props);
    this.state = {
      logged: false,
      token: {},
      profile: {},
    };
  }
...
  _onShowLock() {
    console.log('About to show the lock');
    lock.show({
      closable: false,
      authParams: {
        scope: "openid email name picture headline industry summary location.name offline_access",
      },
    }, (err, profile, token) => {
      if (err) {
        console.log(err);
        return;
      }else{
        console.log(profile);
        this.setState({
          token: token,
          profile: profile,
          logged: true,
        });
        this.saveProfile(profile);
      }
    });
  }

  render() {
    return(
      <View style={styles.container}>
        <Text style={styles.message}>Welcome to the login page</Text>
        <Text style={styles.message}>{this.state.token.accessToken}</Text>
        <TouchableHighlight style={styles.actionButton}
          onPress={() => this._onShowLock()}>
          <Text style={styles.actionButtonText}>Login / Sign up</Text>
        </TouchableHighlight>
      </View>
    );
  }
}

const styles = StyleSheet.create({
...

module.exports = Login;
````

**Comment by Maxyss** [comment]
It doesn't help. I use `AsyncStorage`.

**Comment by allpwrfulroot** [comment]
Oh, so does my saveProfile(). I'm having issues too, filed a support ticket with Auth0 and they've been looking into it.

**Comment by hzalaz** [comment]
@Maxyss can you submit another issue if something is not working with the library? Also AsyncStorage AFAIK is not encrypted so I might not store tokens or user credentials there in without any encryption.

**Comment by hzalaz** [comment]
@devux I am closing this one, please check our [sample application](https://auth0.com/docs/quickstart/native-mobile/react-native-ios/no-api) and feel free to reopen if it doesn't work.
