### ISSUE TITLE
Fail to compile after installing with rnpm with react-native@0.26.2

### ISSUE THREAD

**Issue by victorxw** [auth0/react-native-lock#49]
Hi,

First of all thanks for building this wrapper for react native. It was working fine until I upgrade react native to `0.26.2`. In an earlier time, react was running on `0.25.x` and everything is fine. I did the following steps to upgrade to react native, and the project does not compile unless I remove `react-native-lock` and all Cocoapods related files.

Steps:
```
npm install --save react-native@0.26.2
npm install --save react@15.0.2
npm install --save react-native-lock@0.2.0
react-native upgrade # This leads me to run
npm install --save-dev rnpm-plugin-upgrade@0.26.0
rnpm upgrade
```
After these steps, I cleared `watchman` cache and deleted folder `./ios/build`.

The error I get when building:
```
The following commands produced analyzer issues:
	Analyze Modules/RCTUIManager.m
(1 command with analyzer issues)

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/XXX.app/XXX normal x86_64
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/XXX.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/path to project folder/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/XXX.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:470:13)
    at Object.execFileSync (child_process.js:490:13)
    at _runIOS (runIOS.js:91:34)
    at runIOS.js:24:5
    at tryCallTwo (/path to project folder/node_modules/promise/lib/core.js:45:5)
    at doResolve (/path to project folder/node_modules/promise/lib/core.js:200:13)
    at new Promise (/path to project folder/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/path to project folder/node_modules/react-native/local-cli/cli.js:87:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

Thanks for taking a look at the issue. Comment if any additional information is in need.

**Comment by hzalaz** [comment]
@victorxw tried to reproduce it but couldn't get that error using our sample (which was outdated and now works with 0.26) 
Googling a bit, it looks like this issue https://github.com/facebook/react-native/issues/7308, did you check that?

**Comment by victorxw** [comment]
@hzalaz Thanks for the reply. I was just able to solve the issue with a close look into issues in the Navigator in Xcode workspace.

The error is a missing argument in **'Other Build Flags'**

```
"std::terminate()", referenced from: 
        ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
```

 Refer to this stackoverflow post for solution if anyone encounters similar problems. In my case, `rnpm-plugin-upgrade@0.26.0` failed to fulfill its job. I fixed it by manually adding the missing flag.
> http://stackoverflow.com/questions/37186967/undefined-symbols-for-architecture-x86-64-stdterminate-referenced-from

**Comment by hzalaz** [comment]
Yes, we are going to add that caveat in the quickstart just in case another one has the same issue.

**Comment by victorxw** [comment]
Thanks a bunch!

**Comment by andreafalzetti** [comment]
Had the same issue, it was a problem with the `AppName.xcodeproj/project.pbxproj` file!
