### ISSUE TITLE
how can i display only sign in page

### ISSUE THREAD

**Issue by deepaksisodiya** [auth0/react-native-lock#53]
like

lock.show({
connections: ["signin"]
}, callback);

I do not want signup and reset password button

**Comment by hzalaz** [comment]
@deepaksisodiya `A0LockViewController` supports this with these two flags:

```objc
/**
 * Hides the Sign Up button. By default is `false`.
 */
@property (assign, nonatomic) BOOL disableSignUp;

/**
 * Hides the Reset Password button. By default is `false`.
 */
@property (assign, nonatomic) BOOL disableResetPassword;
```

But we'll have to bridge it in this library (Android has the same flags too).

**Comment by deepaksisodiya** [comment]
What you mean by "we have to bridge it"

You mean like

lock.show({
      disableSignUp:true,
      disableResetPassword:true
    }, callback)

**Comment by hzalaz** [comment]
@deepaksisodiya under the hood this library is a wrapper of the native Locks of each platform so even that functionality is implemented there. I haven't coded the bridge for Javascript, it's there if you are willing to write some lines of code in objc or java.

**Comment by deepaksisodiya** [comment]
@hzalaz hey i created the PR for this issue
https://github.com/auth0/react-native-lock/pull/59
