### ISSUE TITLE
Build failed: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by mbecker** [auth0/react-native-lock#54]
Hi,

just added as described in the README the npm library "_react-native-lock_" and linked it with rnpm:
`rnpm link react-native-lock`

I also added the value "_$(inherited)_" to "_Other Liner Flags_" for all configurations:
![bildschirmfoto 2016-06-01 um 11 09 53](https://cloud.githubusercontent.com/assets/26771/15704131/7e5bf6c2-27e9-11e6-9610-8645c300af4b.png)

I try to run the xcode project with "react native run-ios" and get the the following error:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_A0AuthParameters", referenced from:
      objc-class-ref in libA0RNLock.a(A0LockReact.o)
  "_OBJC_CLASS_$_A0Lock", referenced from:
      objc-class-ref in libA0RNLock.a(A0LockReact.o)
     (maybe you meant: _OBJC_CLASS_$_A0LockReact, _OBJC_CLASS_$_A0LockReactModule )
  "_OBJC_CLASS_$_A0Telemetry", referenced from:
      objc-class-ref in libA0RNLock.a(A0LockReact.o)
  "_OBJC_CLASS_$_A0Token", referenced from:
      l_OBJC_$_CATEGORY_A0Token_$_ReactNative in libA0RNLock.a(A0Token+ReactNative.o)
  "_OBJC_CLASS_$_A0UserIdentity", referenced from:
      l_OBJC_$_CATEGORY_A0UserIdentity_$_ReactNative in libA0RNLock.a(A0UserIdentity+ReactNative.o)
  "_OBJC_CLASS_$_A0UserProfile", referenced from:
      l_OBJC_$_CATEGORY_A0UserProfile_$_ReactNative in libA0RNLock.a(A0UserProfile+ReactNative.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

However the app starts in the simulator but the call of the login screen with "lock.show" doesn't work.

My npm _package.json_ looks like:
```
{
  "name": "safari",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "apphub": "^0.5.1",
    "autoresponsive-react-native": "^1.0.8",
    "react": "0.14.8",
    "react-addons-update": "^15.0.2",
    "react-mixin": "^2.0.2",
    "react-native": "0.25.1",
    "react-native-button": "1.5.0",
    "react-native-drawer": "^2.2.2",
    "react-native-image-picker": "^0.18.15",
    "react-native-linear-gradient": "^1.5.7",
    "react-native-lock": "^0.2.0",
    "react-native-mapbox-gl": "4.1.1",
    "react-native-picker": "^2.0.5",
    "react-native-router-flux": "3.22.23",
    "react-native-vector-icons": "^2.0.2",
    "react-timer-mixin": "^0.13.3"
  }
}
```

The _Podfile_ looks like:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'safari' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for safari

  target 'safariTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
```

For me the error looks like that one of the dependencies of _Lock_ is not build for x86_64. Is that right? So I do need to change my target architecture?

Thanks for your help!

**Comment by mbecker** [comment]
Hi,

just solved it (seems to be a "CocoaPods" issue). As said above I added the value "_$(inherited)_" to "_Other Liner Flags_" for all configurations but for the project and not for the target itself.

So for all guys having the same problem please have a look at the following screenshot and select in the settings your target (and not the project) and add here the value "_$(inherited)_":
![bildschirmfoto 2016-06-01 um 11 31 12](https://cloud.githubusercontent.com/assets/26771/15704929/2040507a-27ed-11e6-9957-8b9bcf188f7d.png)

I'm sorry that I've opened the issue here. Maybe it's worth for anyone else.

**Comment by hzalaz** [comment]
thanks, I'll make it clear in the README
