### ISSUE TITLE
Retrieve profile metadata when calling show

### ISSUE THREAD

**Issue by lostintangent** [auth0/react-native-lock#55]
Is there a way to retrieve either the user or app metadata as part of the profile that is provided upon completion of a call to the show method? I can see how to retrieve it as part of the token, by configuring the authParams/scope option, but I can't figure out why the provided profile object omits it, and it would be great if I didn't need to make an additional API to retrieve the user profile, simply to retrieve the app/user metadata.

**Comment by hzalaz** [comment]
@lostintangent both platforms?

**Comment by lostintangent** [comment]
Apologies, I have only tested this on iOS so far, so my previous comment doesn't necessarily apply to Android.

**Comment by lostintangent** [comment]
Also, just to clarify, the returned profile object does include sub-entries for the user and app metadata, but they're always empty, regardless what the contents are on the server for each user.

**Comment by hzalaz** [comment]
It's a known issue in Android but we thought it was working in iOS. We'll have to patch it there too

**Comment by hzalaz** [comment]
Fixed in master for iOS, we'll patch it for Android

**Comment by lostintangent** [comment]
@hzalaz Awesome! Thanks so much for the quick response.
