### ISSUE TITLE
facebook login doesn't work when facebook app is installed

### ISSUE THREAD

**Issue by stantoncbradley** [auth0/react-native-lock#57]
I am able to successfully launch and login through the facebook login page in the iOS simulator.  However, when test my app on my actual iPhone 6s, when I click the 'Login with Facebook' button from the Auth0 lock screen, the app hangs with a loading circle.  The app is not frozen--I can cancel Lock--but the request to load the facebook login page never resolves.  As mentioned, the flow works fine on the simulator, but not when I test on my device.  Is there any additional configuration I would need to do to get this working on my device?  I am using react-native ^0.26.2 and react-native-lock ^0.2.0.

Thanks!

UPDATE:
Ok I found the at least the beginning of the issue.  Line 344 of `FBSDKLoginManager.m`, `if ([FBSDKInternalUtility isFacebookAppInstalled])`.  In the simulator this returns false and everything works fine.  On my device this returns true, and the resulting code execution hangs.  I stubbed this line to always return false, and it works for now.  Thanks for your time looking into this issue!

**Comment by hzalaz** [comment]
@stantoncbradley I'll need more information on who you setup your application and if you are trying to use FB SDK to authenticate. 
If you want fb login with FB iOS SDK you need to listen to some callbacks in your iOS app's AppDelegate file, it's not documented since it's not officially supported (even though it works in native iOS).

**Comment by stantoncbradley** [comment]
I set up my application using the Auth0 React-Native seed project.  Here is my podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :subspecs => [
'Core',
'RCTImage',
'RCTNetwork',
'RCTText',
'RCTWebSocket'
], :path => '../node_modules/react-native'

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
pod 'Lock-Facebook', '~> 2.2'
```

I see the FBSDKCoreKit and FBSDKLogin kit in my Pods directory, but that's about it.  My guess is the reason Facebook auth doesn't work on my device is it sees I have the facebook app installed and tries to authenticate natively instead of via browser?  I already added the AppDelegate methods mentioned in the quick start:

```
#import "A0LockReact.h"

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  return [[[A0LockReact sharedInstance] lock] handleURL:url sourceApplication:sourceApplication];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {
  return [[[A0LockReact sharedInstance] lock] continueUserActivity:userActivity restorationHandler:restorationHandler];
}
```
and
```
 [[[A0LockReact sharedInstance] lock] applicationLaunchedWithOptions:launchOptions];
```
It would be nice to use the FB SDK to authenticate.  What steps do I need to take to get this to work?

Thanks!

**Comment by hzalaz** [comment]
@stantoncbradley and did you add fb custom scheme in Info.plist file? https://github.com/auth0/Lock-Facebook.iOS#before-you-start-using-lock-facebook

**Comment by stantoncbradley** [comment]
Yessir, and I added fbauth2 to LSApplicationQueriesSchemes

**Comment by hzalaz** [comment]
@stantoncbradley that should be all, I'll have to try to reproduce it

**Comment by stantoncbradley** [comment]
any progress on this?  going to have to fork the project with my hack otherwise D:

**Comment by hzalaz** [comment]
We didn't have time to try to reproduce it since we are working on updating the native lock impl. I don't recall what hack you are referring to but if it's the stub you mention at first is something I'd not recommend doing at all. 
If you have some spare time, can you build a sample project and post it in GH, that will speed up things for me

**Comment by hzalaz** [comment]
@stantoncbradley tried to reproduce and it's working for me. By any chance did you implement both URL handling methods in your AppDelegate like:

```objc
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  NSMutableDictionary *options = [@{} mutableCopy];
  if (sourceApplication) {
    options[UIApplicationOpenURLOptionsSourceApplicationKey] = sourceApplication;
  }
  return [self application:application
                   openURL:url
                   options:options];
}

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
  return [[[A0LockReact sharedInstance] lock] handleURL:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}
```

The former is pre iOS 9 and the later is for iOS 9 and newer versions

**Comment by stantoncbradley** [comment]
@hzalaz I implemented exactly what was listed in the Auth0 docs:
```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  return [[[A0LockReact sharedInstance] lock] handleURL:url sourceApplication:sourceApplication];
}
```
which is slightly different than the latter version you just listed.  I just upgraded to react-native-lock@0.3.0 and still have the same issue.  I also tried 
```
  - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
  return [[[A0LockReact sharedInstance] lock] handleURL:url sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}
```
and facebook login still hangs.  Strange you can't reproduce it.  I appreciate your continued attention in this matter and will continue investigating myself.

Thanks

**Comment by stantoncbradley** [comment]
Ok I think this issue is not happening because I run on device, but because my device has the facebook app installed, and that changes the login flow.  can you please confirm react-native-lock works correctly when facebook app is installed.  I have followed all directions, including trying the code you posted, @hzalaz.  thanks so much!

**Comment by stantoncbradley** [comment]
Alright, getting ready to release my app and really need to get this fixed.  Started from the ground up with a fresh RN 0.30 install, lock 0.3.0, fb cocoa pod ~2.2, followed everything in the tutorial 100%.  Still having this issue!!  Do I need to also install the FBSDK?  just the regular iOS fbskd or react-native-fbsdk?

as it stands I am either going live w/ the hack until I switch from Auth0 which I don't want to do.  Please help!

**Comment by stantoncbradley** [comment]
UPDATE:  I tried my original credentials on the

**Comment by stantoncbradley** [comment]
I know you are very busy, can you tell me if my workaround using web authentication instead of facebook app authentication is at all a security vulnerability?  (setting line 344 of FBSDKLoginManager.m to always be false).  This issue is holding up release.  Will my workaround work for now or do I need to look at other auth strategies, or can you see why Auth0 doesn't work with facebook app login?

Thanks

**Comment by hzalaz** [comment]
Sorry but I don't follow what is wrong. If Facebook SDK is using Safari to authenticate in iOS 9+, that's their intender behaviour (check [this post](https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/)). 

I'd advise against changing any code inside `Pods` folder since any `pod install` will remove them, specially a third party lib.

There is an option in their SDK to force using system credentials (the ones configured in iOS) and we'll eventually add them in our integration. Also tested the integration and is working (it uses safari since it's what FB SDK does) so let me know if it doesn't work in your app.

**Comment by stantoncbradley** [comment]
thanks for getting back to me.  let me try to explain again, Auth0 + FBSDK work fine when I don't have the facebook app installed.  My problem is when I do have the facebook app installed then FBSDK automatically tries to use my facebook app to authenticate, and execution hangs there.

I agree, I'm not thrilled overwriting pod code, and I really want to fix this.

Can you please test the Auth0 integration when facebook app is installed?  my problem is when Auth0 + FBSDK try to use the app to authenticate (which it does automatically if facebook app is installed).

Thanks, let me know if I can clarify/provide any more information!

**Comment by stantoncbradley** [comment]
upon removing `'Lock-Facebook', '~> 2.2'` from my podfile and doing a fresh pod install, facebook authentication seems to work.  Thanks!

Just FYI, the docs still instruct to include the Lock-Facebook pod.  That can probably be removed
