### ISSUE TITLE
SMS phone number placeholder says 'email'

### ISSUE THREAD

**Issue by anurag** [auth0/react-native-lock#58]
<img width="347" alt="screen shot 2016-06-06 at 10 36 46 pm" src="https://cloud.githubusercontent.com/assets/59905/15847028/5b0e830e-2c37-11e6-8118-b26e609d8846.png">

**Comment by simonbdev** [comment]
+1
getting this as well. Also, mine won't send sms - I get the error 'There was an error sending the SMS code'?

**Comment by hzalaz** [comment]
This was fixed in the latest version of Lock for iOS. Running a `pod update` will update it.

**Comment by MikhailVasiliev** [comment]
+1
have the same issue
