### ISSUE TITLE
Enable / Disable Signup

### ISSUE THREAD

**Issue by cancan101** [auth0/react-native-lock#6]
The README shows a button for signup on the lock, but my lock does not show this option. How do I expose the signup option?

![image](https://cloud.githubusercontent.com/assets/51059/11314338/9e31c672-8fb2-11e5-94f2-ca58f6c85d19.png)

**Comment by hzalaz** [comment]
Check that you are using the latest version since we had an issue with some default values. If you have the latest version check your connection settings to see if you have disabled the signups (In Auth0 Dashboard)

**Comment by hzalaz** [comment]
@cancan101 closing this one, if it's still an issue please reopen it.
