### ISSUE TITLE
Emails not being returned from Twitter even after app is whitelisted for emails.

### ISSUE THREAD

**Issue by sbefort** [auth0/react-native-lock#66]
I am not sure if this is a coding problem on my end or a bug with React Native Lock:

http://stackoverflow.com/questions/37999972/twitter-whitelisted-my-application-so-i-can-retrieve-user-email-but-still-not-g

**Comment by sbefort** [comment]
Related rule:  [https://github.com/auth0/rules/blob/master/rules/get-twitter-email.md](https://github.com/auth0/rules/blob/master/rules/get-twitter-email.md)

`request({
    url: url + '?include_email=true',
    headers: {
      'Authorization': 'OAuth ' + auth
    }
  }, function(err, resp, body) {
    if (err || resp.statusCode !== 200) {
      return callback(new Error('Error retrieving email from twitter: ' + body || err));
    }
    var result;
    try {
      result = JSON.parse(body);
    } catch (e) {
      return callback(new Error('Invalid JSON returned by Twitter'));
    }
    if (!result.email) {
      // Might not want to fail in this case
      return callback(new Error('Twitter did not return an email address'));
    } else {
      user.email = result.email;
      return callback(null, user, context);
    }
  });`

Does React Native Lock support the `url + '?include_email=true'` query string?

**Comment by hzalaz** [comment]
@sbefort seems to me that it's outside the scope of this lib. Please go to https://support.auth0.com to get better support since we only handle issues for this library not the auth0 platform

**Comment by sbefort** [comment]
It is a problem with the library.  Auth0 supports it but this library does not.
