### ISSUE TITLE
Bypassing the lock UI

### ISSUE THREAD

**Issue by calclavia** [auth0/react-native-lock#67]
Is there a way to bypass the lock UI and directly authenticate with a social provider?

In my app, I have buttons 'login to Facebook', and I hope to be able to have the user not need to tap twice (once on login to Facebook, then on Auth0's login to Facebook button).

**Comment by hzalaz** [comment]
There is a method in lock https://github.com/auth0/react-native-lock/blob/master/auth0-lock.js#L40 to authenticate with a specific connection without showing lock. Sadly it only works in iOS now.

We are evaluating adding it for Android but no ETA
