### ISSUE TITLE
How to use lock.usersAPI?

### ISSUE THREAD

**Issue by allpwrfulroot** [auth0/react-native-lock#68]
I want to add 'myData': { first: false, second: true, third: 'Bubbles'} to a user's user_metadata

```js
      const token = this.state.token.idToken;
      lock.usersAPI(token)
        .patch(this.state.profile.identities.user_id, {
          'myData': data,
        })
        .then(response => console.log(response))
        .catch(error => console.log(error));
```
Error returned via console.log(error): must supply an identifier of the user to be updated

Can you provide more detail on which tokens/user_id it's looking for, and the correct usage of the lock.usersAPI() call?

**Comment by allpwrfulroot** [comment]
I've tried about two dozen different ways of doing this and none of them work: invariably, I get back "must supply an identifier of the user to be updated" no matter what identifier or token or whatever I use. Help? This is blocking my launch.

**Comment by nikolaseu** [comment]
@allpwrfulroot you should use the auth0's user_id, not the ones in identities array.
try with
`.patch(this.state.profile.user_id, {`

**Comment by allpwrfulroot** [comment]
Yup, tried that too. And lots of permutations of user_id, accessToken, idToken, etc. I've even tried different authentications (email/password and linkedin). So far nothing has worked, all the same error.

**Comment by hzalaz** [comment]
@allpwrfulroot  `this.state.profile.user_id`  has a non-null value?. Also if it's urgent and you have a paid plan, you can go to https://support.auth0.com to get faster support since we are not always checking GH issues.

**Comment by allpwrfulroot** [comment]
Thanks for that, sanity checked and it was indeed undefined: it's userId not user_id. Derp x2.
