### ISSUE TITLE
Build success on Simulator but failed on phone. "library not found for -lA0RNLock"

### ISSUE THREAD

**Issue by wuzhuzhu** [auth0/react-native-lock#70]
> ld: library not found for -lA0RNLock
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by wuzhuzhu** [comment]
@brennanmeadowcroft select "n" when console rnpm link ask you overwrite or not

**Comment by brennanmeadowcroft** [comment]
I tried that and no luck.

**Comment by brennanmeadowcroft** [comment]
@wuzhuzhu Did you add A0RNLock to your project in XCode?  Try this:

1. Right click on Libraries and select "Add Files To <App Name>..."
2. Navigate to `node_modules/react-native-lock/ios`
3. Select `AORNLock.xcodeproj` and click Add
4. Compile the project

`rnpm link react-native-lock` might work but I've had mixed success with it depending on the project I'm trying to link.

**Comment by ericmasiello** [comment]
I'm having the same issue as @brennanmeadowcroft . I'm on React Native 30. Anyone have any luck yet?

**Comment by brennanmeadowcroft** [comment]
@ericmasiello Do you have `Pods.xcodeproj` in `Libraries/`?  

If not, try right clicking on Libraries, select "Add Files To..." and go under `<Your Project>/ios/Pods/` and select `Pods.xcodeproj`.  The problem for me was that XCode didn't know where to find all those libraries.

**Comment by ericmasiello** [comment]
thanks @brennanmeadowcroft. That helped but now i'm getting a new error:

```
Undefined symbols for architecture x86_64:
  "std::terminate()", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "operator delete[](void*)", referenced from:
      -[RCTJSCExecutor dealloc] in libReact.a(RCTJSCExecutor.o)
      executeRandomAccessModule(RCTJSCExecutor*, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
      readRAMBundle(std::__1::unique_ptr<__sFILE, int (*)(__sFILE*)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
      RandomAccessBundleData::~RandomAccessBundleData() in libReact.a(RCTJSCExecutor.o)
  "operator new[](unsigned long)", referenced from:
      executeRandomAccessModule(RCTJSCExecutor*, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
      readRAMBundle(std::__1::unique_ptr<__sFILE, int (*)(__sFILE*)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "___gxx_personality_v0", referenced from:
      -[RCTJavaScriptContext initWithJSContext:onThread:] in libReact.a(RCTJSCExecutor.o)
      -[RCTJavaScriptContext init] in libReact.a(RCTJSCExecutor.o)
      -[RCTJavaScriptContext invalidate] in libReact.a(RCTJSCExecutor.o)
      RCTNSErrorFromJSError(RCTJSCWrapper*, OpaqueJSContext const*, OpaqueJSValue const*) in libReact.a(RCTJSCExecutor.o)
      +[RCTJSCExecutor runRunLoopThread] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor init] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor initWithUseCustomJSCLibrary:] in libReact.a(RCTJSCExecutor.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Any ideas?

**Comment by brennanmeadowcroft** [comment]
@ericmasiello Did you use `rnpm link` or did you follow the instructions explicitly?

**Comment by ericmasiello** [comment]
@brennanmeadowcroft i tried both ways actually.

**Comment by ericmasiello** [comment]
I ended up cloning the Pepperoni project because I know they had Auth0 integration. I was able to get that one working. Although I _believe_ Pepperoni was a version or two behind on React Native.

**Comment by hzalaz** [comment]
@ericmasiello you need to run `rnpm link` and check that the proper compiler flags are set for all Xcode targets. The README has a bit more info [here](https://github.com/auth0/react-native-lock#cocoapods-warning) and [also here](https://github.com/auth0/react-native-lock#compile-error-react-native-0260).

Closing this issue for now please reopen a new if needed.

**Comment by Msspl-PrashenjeetRoy** [comment]
@brennanmeadowcroft Thank you very much, I was trying this from 3 hours and just getting full of folder not found error. Now after adding pod file to library it's working smoothly. Thanks again.

**Comment by lon-io** [comment]
@brennanmeadowcroft Thanks so much man! You helped solve an issue had been battling for over a month!
