### ISSUE TITLE
Seed Project Will Not Compile In XCode

### ISSUE THREAD

**Issue by brennanmeadowcroft** [auth0/react-native-lock#73]
I downloaded the seed project from the documentation site ([React Native iOS Quickstart](https://auth0.com/docs/quickstart/native/react-native-ios)) and ran it without any modifications using the same conditions the quickstart said it has been tested in:
- React Native 0.26.0
- Node 4.3
- CocoaPods 1.0.0

It compiled and ran fine in the simulator using `react-native run-ios`.

When I tried to compile it in XCode, it failed with the following issue:
```
ld: warning: directory not found for option '-L/Users/brennan/Library/Developer/Xcode/DerivedData/Auth0Sample-eladxhulkghakbblmlqoogfnnarc/Build/Products/Debug-iphonesimulator/AFNetworking'
ld: warning: directory not found for option '-L/Users/brennan/Library/Developer/Xcode/DerivedData/Auth0Sample-eladxhulkghakbblmlqoogfnnarc/Build/Products/Debug-iphonesimulator/CocoaLumberjack'
ld: warning: directory not found for option '-L/Users/brennan/Library/Developer/Xcode/DerivedData/Auth0Sample-eladxhulkghakbblmlqoogfnnarc/Build/Products/Debug-iphonesimulator/Lock'
ld: warning: directory not found for option '-L/Users/brennan/Library/Developer/Xcode/DerivedData/Auth0Sample-eladxhulkghakbblmlqoogfnnarc/Build/Products/Debug-iphonesimulator/Masonry'
ld: warning: directory not found for option '-L/Users/brennan/Library/Developer/Xcode/DerivedData/Auth0Sample-eladxhulkghakbblmlqoogfnnarc/Build/Products/Debug-iphonesimulator/SimpleKeychain'
ld: warning: directory not found for option '-L/Users/brennan/Library/Developer/Xcode/DerivedData/Auth0Sample-eladxhulkghakbblmlqoogfnnarc/Build/Products/Debug-iphonesimulator/TouchIDAuth'
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The problem could be solved by manually linking the `Pods/Pods.xcodeproj`.

It seems there may be a problem with `rnpm link` or `pod install` in that it doesn't like the Pod xcode project to the libraries.  I don't have any experience with making rnpm work with a given project... is this an easy fix or does it just need to be documented.

**Comment by hzalaz** [comment]
Thanks for reporting this, we'll review the sample and fix it.
Also this is not the right place to report issues from our samples, the docs site has a feedback tab where you can submit these issue and get a faster response
