### ISSUE TITLE
Inconsistent Android and iOS profile upon login

### ISSUE THREAD

**Issue by calclavia** [auth0/react-native-lock#74]
When logging into a social provider on iOS, the data response from the result contains the identities object. However, when logging into Android, the data response does not contain the response object.
```js
authParams: {
            scope: 'openid name offline_access',
            device: 'Mobile device'
          }
```

React Native v0.27
Lock v0.3.0

**Comment by hzalaz** [comment]
Yes, the android bridge does not convert all profile information.
