### ISSUE TITLE
Error linking react-native-lock with iOS

### ISSUE THREAD

**Issue by dwilt** [auth0/react-native-lock#75]
I'm trying to install react-native-lock into my existing react native project but am getting this error when trying to run `rnpm link react-native-lock`:

```bash
dwilt:gjs-app dwilt$ rnpm link react-native-lock
Preparing to link react-native-lock for iOS
Checking CocoaPods...
CocoaPods already installed
rnpm-link info Linking react-native-lock android dependency 
rnpm-link info Android module react-native-lock has been successfully linked 
rnpm-link ERR! It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/dwilt/Projects/GJS/gjs-app/ios/AirshipKit/AirshipKit.xcodeproj/project.pbxproj' 
Please file an issue here: https://github.com/rnpm/rnpm/issues 
```

**Comment by Kureev** [comment]
Looks like `project.pbxproj` has been removed from git.

**Comment by hzalaz** [comment]
The file is still there also a sample app or some repro steps will be useful to troubleshoot this

**Comment by hzalaz** [comment]
@dwilt checked your initial comment again and `AirshipKit` is not part of our libs. I know the react-native upgrade is far from perfect but I am afraid I can't help you with that.

**Comment by dwilt** [comment]
@hzalaz Ahhh, thank you. This was an artifact. I got your product names mixed up. Will close this issue as well as the one on https://github.com/rnpm/rnpm/issues/193. Seems odd that it was somehow running into UrbanAirship's code while that was running.

That being said, I am using OneSignal as a Push Notification provider for the app and they use CocoaPods as well. It asked me if I wanted to overwrite my Podfile and I did, but now my OneSignal project is uninstalled:

```
Found an existing Podfile, Do you want to override it? [N/y]
y
Adding Podfile to iOS project
Installing Pods
Analyzing dependencies
Removing OneSignal <-------------------------------- Uninstalled OnSignal
Downloading dependencies
Installing AFNetworking (3.1.0)
Installing CocoaLumberjack (2.3.0)
Installing Lock (1.26.1)
Installing Masonry (0.6.4)
Installing SimpleKeychain (0.7.0)
Installing TouchIDAuth (0.2.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 6 total pods installed.
dwilt:gjs-app dwilt$ 
```
Am I able to add OneSignal back into the Podfile somewhere and it should reinstall itself? It looked like this previously:

```
target "GreatJonesStreet" do
    pod 'OneSignal'
end 
```

**Comment by hzalaz** [comment]
yes, and running `pod install`

**Comment by dwilt** [comment]
Just to be safe, as I'm unfamiliar with CocoaPods, where would you put it:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GreatJonesStreet' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GreatJonesStreet

  target 'GreatJonesStreetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
```

**Comment by dwilt** [comment]
Got it, just put it in the first `target 'GreatJonesStreet' do`. This seems to have worked. Thanks @hzalaz !!!!!!

**Comment by dwilt** [comment]
@hzalaz Another issue.. after installing and trying to run my project, I'm getting this error:

![image](https://cloud.githubusercontent.com/assets/1065539/17254756/fc39d452-556a-11e6-8d59-ba03e24c0fa0.png)

I see that you guys are aware that this one error might happen:

```
"std::terminate()", referenced from:
        ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
```

 and thus provide steps to follow. If you look at my screenshot though, I did verify that `-lc++` is in the `Other Linker Flags` and set for both configurations and it still isn't working. Let me know if you'd like me to open an issue somewhere. I tried to run this in that brand new scaffolded project from React Native and am getting the same thing:

![image](https://cloud.githubusercontent.com/assets/1065539/17255042/4a6c5e8c-556c-11e6-9ff1-9cc819867970.png)

**Comment by dwilt** [comment]
@hzalaz should I open up another issue for this? Let me know if you're seeing the same thing as this is holding up our project.

**Comment by sbefort** [comment]
Same problem after upgrading React to 0.30.  `-lc++` is already in `Other Linker Flags`

**Comment by dwilt** [comment]
I think this is the same as https://github.com/auth0/react-native-lock/issues/76
