### ISSUE TITLE
Build fails with vanilla project

### ISSUE THREAD

**Issue by sbefort** [auth0/react-native-lock#76]
Build fails with vanilla project using React Native 0.30.  Steps to reproduce:

```
react-native init myproject
cd myproject
react-native run-ios
```

At this point everything is fine.  The "Welcome to React Native" screen appears.  Then Auth0 Lock is installed:

```
npm install --save react-native-lock
rnpm link react-native-lock

Pod installation complete! There are 4 dependencies from the Podfile and 6 total
pods installed.
```

`react-native run-ios`

Build errors:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/myproject.app/PlugIns/myprojectTests.xctest/myprojectTests normal x86_64
(1 failure)
/Users/nomad/Mobile/myproject/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: xcodebuild process exited with code 65
    at ChildProcess.xcodeBuildProcess.on.code (runIOS.js:102:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

`-lc++` is already listed in `Other Linker Flags` so that is not the issue.

**Comment by hzalaz** [comment]
Seems the "vanilla project" for iOS now builds a test target (which I don't know why it's there at all), and is missing the `-lc++` flag since the errors in the log are that the C++ symbols cannot be found. So make sure that that flag is added in *both* targets of your project

**Comment by sbefort** [comment]
You are right.  Selected the target `myprojectTests` and the `-lc++` flag was not there for that target.  Added the `-lc++` flag and it fixed the issue.  Thanks.

**Comment by awesomejerry** [comment]
Can you tell me how to add -lc++ flag to the test target? Can't find Other Linker Flags in Linking in Build Setting

**Comment by sbefort** [comment]
![upool xcodeproj 2016-09-04 23-06-05](https://cloud.githubusercontent.com/assets/787262/18237205/3dceac34-72f4-11e6-8dea-b360874a5d32.png)

**Comment by sbefort** [comment]
upool is the name of my app.  Click on the name of your app and there should be a drop-down arrow to select other targets.

**Comment by awesomejerry** [comment]
Thanks, but I didn't see any place that I can add `-lc++` flags to the `projectTest` target

**Comment by sbefort** [comment]
If you select that target and search/filter by the word "linker," does it not show up?

**Comment by awesomejerry** [comment]
OMG, it was hidden by the filter. I should choose `All` filter. Now it works! Thanks again!
<img width="167" alt="2016-09-05 12 16 32" src="https://cloud.githubusercontent.com/assets/6601073/18237344/b3c1022a-7362-11e6-8f10-62e24105db0e.png">

**Comment by code-h** [comment]
@sbefort  GOOD
