### ISSUE TITLE
Command is not working

### ISSUE THREAD

**Issue by lobo** [auth0/react-native-lock#78]
`rnpm link react-native-lock` is not working at the moment.

**Comment by dwilt** [comment]
This was started originally from an email I sent asking for help but was closed via https://github.com/auth0/react-native-lock/issues/75. I've since opened another issue that seems to be the same as https://github.com/auth0/react-native-lock/issues/76

**Comment by YaweiChen** [comment]
+1

**Comment by dwilt** [comment]
This issue can be closed as its the same as #76

**Comment by lobo** [comment]
Closing the issue, due to #76
