### ISSUE TITLE
 48 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by ShailendraBarewar** [auth0/react-native-lock#80]
Ld /Users/mac/Library/Developer/Xcode/DerivedData/Soie-drazaefwicwmvjcwxyfxnicdkigb/Build/Products/Debug-iphonesimulator/Soie.app/Soie normal x86_64
    cd "/Users/mac/Documents/imp Code/Soie 5th August "
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/mac/Library/Developer/Xcode/DerivedData/Soie-drazaefwicwmvjcwxyfxnicdkigb/Build/Products/Debug-iphonesimulator -L/Users/mac/Documents/imp\ Code/Soie\ 5th\ August\ /Soie/PaymentsSDK -L/Users/mac/Documents/imp\ Code/Soie\ 5th\ August\ /Soie/Utilities -F/Users/mac/Library/Developer/Xcode/DerivedData/Soie-drazaefwicwmvjcwxyfxnicdkigb/Build/Products/Debug-iphonesimulator -F/Users/mac/Documents/imp\ Code/Soie\ 5th\ August\ /Soie -filelist /Users/mac/Library/Developer/Xcode/DerivedData/Soie-drazaefwicwmvjcwxyfxnicdkigb/Build/Intermediates/Soie.build/Debug-iphonesimulator/Soie.build/Objects-normal/x86_64/Soie.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=8.1 -framework FacebookSDK -lsqlite3.0 -lz -framework CoreTelephony -framework Accelerate -framework QuartzCore -framework CoreData -lAdIdAccess -lPaymentsSDK -framework SystemConfiguration -lGoogleAnalyticsServices -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/Soie-drazaefwicwmvjcwxyfxnicdkigb/Build/Intermediates/Soie.build/Debug-iphonesimulator/Soie.build/Objects-normal/x86_64/Soie_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/Soie-drazaefwicwmvjcwxyfxnicdkigb/Build/Products/Debug-iphonesimulator/Soie.app/Soie

duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIUtil.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIUtil.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIEcommerceFields.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIEcommerceFields.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIDefaultLogger.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIDefaultLogger.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAITrackerImpl.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAITrackerImpl.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIDataStore.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIDataStore.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIHitFormat.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIHitFormat.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAICoreDataUtil.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAICoreDataUtil.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIHitUtil.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIHitUtil.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIRequestBuilder.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIRequestBuilder.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIStringUtil.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIStringUtil.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAICampaign.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAICampaign.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIURLConnection.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIURLConnection.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAITrackedViewController.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAITrackedViewController.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIUncaughtExceptionHandler.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIUncaughtExceptionHandler.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIExceptionParser.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIExceptionParser.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIFields.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIFields.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIDictionaryBuilder.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIDictionaryBuilder.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAITrackerModel.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAITrackerModel.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIBatchingDispatcher.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIBatchingDispatcher.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIUsageTracker.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIUsageTracker.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAISqlStore.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAISqlStore.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAICompressionUtil.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAICompressionUtil.o)
duplicate symbol _llvm.cmdline in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIAnalyticsPropertiesStore.o)
duplicate symbol _llvm.embedded.module in:
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAI.o)
    /Users/mac/Documents/imp Code/Soie 5th August /Soie/Utilities/libGoogleAnalyticsServices.a(GAIAnalyticsPropertiesStore.o)
ld: 48 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have try so many things but this issue is not resolve plz help me..

**Comment by hzalaz** [comment]
Closing this one, if it's still an issue please reopen and upload a sample project we can check.
