### ISSUE TITLE
Valid email is triggering invalid email popup

### ISSUE THREAD

**Issue by dwilt** [auth0/react-native-lock#81]
I think there is a regex pattern issue here. Our client has an email - someone@gjs.press - and when they're trying to login, it's giving an invalid email error:

![image](https://cloud.githubusercontent.com/assets/1065539/17593909/54a06cf6-5f9c-11e6-93fa-9d18b467d198.png)
![image](https://cloud.githubusercontent.com/assets/1065539/17593927/631bdce8-5f9c-11e6-9391-b2def5a7d641.png)

```
"react-native-lock": "^0.3.0",
"react": "15.2.1",
"react-native": "0.28.0",
```
iOS 9.3 iPhone 6 simulator

**Podfile**
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GreatJonesStreet' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GreatJonesStreet
  pod 'OneSignal'
  pod 'Branch'

  # Auth0 Lock
  pod 'Lock', '~> 1.26'
  pod 'Lock/TouchID'
  pod 'Lock/SMS'
  pod 'Lock/Email'

  target 'GreatJonesStreetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

Node: `5.7.1`
NPM: `3.6.0`

**Comment by hzalaz** [comment]
Closing in favor of auth0/Lock.iOS-OSX/issues/248

**Comment by dwilt** [comment]
@hzalaz Thanks. Any idea when this will be available in a release?

**Comment by hzalaz** [comment]
Just run `pod update` in your `ios` folder. Lock for iOS *1.26.2* fixes this issue

**Comment by dwilt** [comment]
Awesome, this worked. Thanks @hzalaz!
