### ISSUE TITLE
Failure to link

### ISSUE THREAD

**Issue by Jorenm** [auth0/react-native-lock#86]
React Native Version 0.30.0
NPM Version: 3.9.5
react-native-lock Version: 0.3.0
Windows 10

I'm trying to link the react-native-lock library, but am getting an error.

I'm running: "rnpm link react-native-lock" as per the docs, but getting the following error:

rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues

I posted an issue to react-native, but was suggested to post it here.

**Comment by hzalaz** [comment]
Need a little more info, can you add the log since that error provides little info?. Also we didn't test the library in Windows since you need iOS build tools that are only available in macOS

**Comment by Jorenm** [comment]
How do I get the log? Also what build tools are those? I was only planning to deploy to Android.

**Comment by hzalaz** [comment]
the full console log output you have when trying to link, I don't have a windows installation at hand to try it.

**Comment by vzhen** [comment]
@hzalaz I have the exactly same issue on Windows 7.  Here is the full console log output
![capture](https://cloud.githubusercontent.com/assets/1941395/17866768/6c1aaa58-68da-11e6-8014-4a54568fbd55.PNG)

**Comment by Jorenm** [comment]
Yep. Exactly that. If there are more logs hidden somewhere beyond that, I've no idea where they'd be. --verbose doesn't seem to be an option.

**Comment by hzalaz** [comment]
Probably the pre/post link scripts are executed and they are bash scripts but I'd have to try it to be sure. Can you try using `react-native link` instead ?

**Comment by Jorenm** [comment]
More verbose error from that:

rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues
C:\node\react_native\AwesomeProject\node_modules\promise\lib\done.js:10
      throw err;
      ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at makeCommand.js:12:28
    at link.js:25:3
    at Promise (link.js:24:29)
    at link.js:121:11
    at process._tickCallback (node.js:369:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)

**Comment by vzhen** [comment]
here is mine
![capture](https://cloud.githubusercontent.com/assets/1941395/17867308/894a2548-68dc-11e6-90b8-401e88724612.PNG)

**Comment by hzalaz** [comment]
Try removing from the package.json the following lines:

```son
  "rnpm": {
    "commands": {
      "prelink": "node_modules/react-native-lock/bin/prepare.sh",
      "postlink": "node_modules/react-native-lock/bin/cocoapods.sh"
    }
  }
```

so it doesn't run a bash script in windows

**Comment by Jorenm** [comment]
Successfully ran with those lines removed:

rnpm-link info Linking react-native-lock android dependency
rnpm-link info Android module react-native-lock has been successfully linked
rnpm-link info Linking react-native-lock ios dependency
rnpm-link info iOS module react-native-lock has been successfully linked

**Comment by vzhen** [comment]
LOL.  work like a charms

**Comment by viniciusgati** [comment]
> {
>   "name": "VibeCRM",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "start": "node node_modules/react-native/local-cli/cli.js start",
>     "test": "jest"
>   },
>   "dependencies": {
>     "eslint-config-rallycoding": "^3.1.0",
>     "native-base": "^0.5.13",
>     "react": "15.3.2",
>     "react-native": "0.36.1",
>     "react-redux": "^4.4.5",
>     "realm": "^0.14.3",
>     "redux": "^3.6.0"
>   },
>   "jest": {
>     "preset": "jest-react-native"
>   },
>   "devDependencies": {
>     "babel-jest": "16.0.0",
>     "babel-preset-react-native": "1.9.0",
>     "jest": "16.0.2",
>     "jest-react-native": "16.1.0",
>     "react-test-renderer": "15.3.2"
>   }
> }
> 

still get the error...

> 
> $ react-native link realm
> rnpm-install info Linking realm android dependency
> rnpm-install info Android module realm has been successfully linked
> rnpm-install info Linking realm ios dependency
> rnpm-install WARN ERRGROUP Group 'Frameworks' does not exist in your XCode project. We have created it automa
> rnpm-install info iOS module realm has been successfully linked
> rnpm-install ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
> Please file an issue here: https://github.com/facebook/react-native/issues
> 
> spawn UNKNOWN
>

**Comment by herlon214** [comment]
```json
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "mapbox": "^1.0.0-beta5",
    "react": "~15.4.0-rc.4",
    "react-native": "0.38.0",
    "react-native-animatable": "^1.1.0",
    "react-native-drawer": "^2.3.0",
    "react-native-image-progress": "^0.6.0",
    "react-native-lock": "^0.4.0",
    "react-native-mapbox-gl": "^5.1.0",
    "react-native-maps": "^0.11.0",
    "react-native-md-textinput": "^2.0.4",
    "react-native-navbar": "^1.5.4",
    "react-native-parallax": "^0.3.0",
    "react-native-progress": "^3.2.0",
    "react-native-router-flux": "^3.37.0",
    "react-native-simple-store": "^1.1.0",
    "react-native-splash-screen": "^1.0.9",
    "react-native-swiper": "^1.5.4",
    "react-native-vector-icons": "^3.0.0",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-jest": "17.0.2",
    "babel-preset-react-native": "1.9.0",
    "jest": "17.0.3",
    "jest-react-native": "17.0.3",
    "react-test-renderer": "~15.4.0-rc.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

Resulting in this error:

```ssh
$ rnpm link react-native-lock
rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues
(node:6548) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: spawn UNKNOWN
(node:6548) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ldunphy1** [comment]
@hzalaz Will this app still work properly in production with those lines removed?

**Comment by mikebridge** [comment]
@hzalaz I also get this error with a brand new project created with `react-native init Auth0Test` on Windows 10.  

```json
{
  "name": "Auth0Test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.42.0",
    "react-native-lock": "^0.5.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

```cmd
> npm install --save react-native-lock
Auth0Test@0.0.1 c:\Users\Mike\AndroidStudioProjects\Auth0Test
`-- react-native-lock@0.5.0

> react-native link react-native-lock
Scanning 550 folders for symlinks in c:\Users\Mike\AndroidStudioProjects\Auth0Test\node_modules (16ms)
rnpm-install ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/facebook/react-native/issues

spawn UNKNOWN
```

**Comment by mikebridge** [comment]
I added an issue at [https://github.com/facebook/react-native/issues/12687](https://github.com/facebook/react-native/issues/12687).

**Comment by hzalaz** [comment]
@mikebridge it will fail since it will try to run a Mac command (CocoaPods) in Windows. The workaround I mentioned in this issue will fix. Making this work out of the box in Windows in not a high priority item right now

**Comment by hzalaz** [comment]
@ldunphy1 you need to bring them back when you upload or test your iOS app in OS X, something you will need to do if you plan to ship an iOS app

**Comment by mikebridge** [comment]
@ldunphy1 Thanks—right now I'm just looking at android so I guess I can work around it.

**Comment by ldunphy1** [comment]
@hzalaz I'm also working on android, not ios.

**Comment by jeungsook** [comment]
I don't have those in my package.json and I get this error.

C:\Users\Jeung-Sook\Spots>rnpm link react-native-lock
rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues
(node:13000) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: spawn UNKNOWN
(node:13000) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

How do I fix this?
