### ISSUE TITLE
Error sending the email code. 

### ISSUE THREAD

**Issue by naineshg** [auth0/react-native-lock#94]
I'm getting this error in Android version of my app. It works fine in iOS.

<img width="374" alt="screen shot 2016-10-06 at 4 07 52 pm" src="https://cloud.githubusercontent.com/assets/3132196/19168652/225510a2-8bdf-11e6-86a6-f6146168eb86.png">

Everything is configured properly as mentioned in README.

**Comment by NaineshG** [comment]
@hzalaz Can you take look into this issue?

**Comment by hzalaz** [comment]
@naineshg if it's still an issue please contact us via https://support.auth0.com. It could be that either the email connection is disabled or not properly configured in your tenant so we need that information
