### ISSUE TITLE
Compile from the Xcode error - library not found for -lAFNetworking

### ISSUE THREAD

**Issue by jayhuang75** [auth0/react-native-lock#99]
Hello,

The react-native-lock is working fine in simulator only when we open the from react-native run-ios.

Once we open the project Xcode. And try to compile from the Xcode. we have this error.

`ld: library not found for -lAFNetworking`

Please advise.

Thanks

**Comment by jayhuang75** [comment]
Anyone still support this? :)

**Comment by hzalaz** [comment]
You  are supposed to use it from react-native cli since using it from Xcode requires a bit of knowledge of how cocoapods and Xcode works. If you really need to use it please try opening the .xcworkspace file since I think you opened the .xcodeproj.

**Comment by jayhuang75** [comment]
Hello @hzalaz ,

Thanks for the advice. :)

**Comment by noahdesu** [comment]
Another way that worked for me so that I could compile in xcode was to add the ios/Pods project to the Library folder.

**Comment by hzalaz** [comment]
I'd avise to avoid adding the CP folder to the Xcode project since it could break it if you are not careful enough. The safe way is to use workspace file

**Comment by noahdesu** [comment]
@hzalaz thanks for the advice. i'm very new at this stuff and don't want to lead anyone down a bad path :)
